/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import cruds.ShortCourseCrud;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author YuryAlencar
 */
public class AdvancedConsultShortCourse extends javax.swing.JFrame {
    
    private JList jListNamesShortCourses;
    private List<String> displayList;
    /**
     * Creates new form AdvancedConsultShortCourse
     */
    public AdvancedConsultShortCourse(JList jListNamesShortCourses) {
        initComponents();
        this.jListNamesShortCourses = jListNamesShortCourses;
        
        this.setTitle("RP II - Consulta Avançada");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAdvancedConsultTitle = new javax.swing.JLabel();
        jLabelAdvancedConsultAuthor = new javax.swing.JLabel();
        jButtonAdvancedConsultConsult = new javax.swing.JButton();
        jTextAdvancedConsultTitle = new javax.swing.JTextField();
        jTextAdvancedConsultAuthor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelAdvancedConsultTitle.setText("Título:*");

        jLabelAdvancedConsultAuthor.setText("Autor:*");

        jButtonAdvancedConsultConsult.setText("Consultar");
        jButtonAdvancedConsultConsult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdvancedConsultConsultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAdvancedConsultTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextAdvancedConsultTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAdvancedConsultAuthor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextAdvancedConsultAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAdvancedConsultConsult, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAdvancedConsultTitle)
                    .addComponent(jTextAdvancedConsultTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAdvancedConsultAuthor)
                    .addComponent(jTextAdvancedConsultAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonAdvancedConsultConsult)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void displayList() {
        DefaultListModel mList = new DefaultListModel();
        
        for(String element : displayList){
            mList.addElement(element);
        }
        jListNamesShortCourses.setModel(mList);
    }

    private void jButtonAdvancedConsultConsultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdvancedConsultConsultActionPerformed
        // TODO add your handling code here:
        if(jTextAdvancedConsultAuthor.getText().trim().equals("") || jTextAdvancedConsultTitle.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "É necessário o preenchimento de todos os campos(*) para realizar a consulta avançada");
        }else{
            
            displayList = ShortCourseCrud.advancedConsult(jTextAdvancedConsultTitle.getText(),jTextAdvancedConsultAuthor.getText());
            displayList();
            this.dispose();
        }
    }//GEN-LAST:event_jButtonAdvancedConsultConsultActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdvancedConsultShortCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdvancedConsultShortCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdvancedConsultShortCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdvancedConsultShortCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdvancedConsultShortCourse(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdvancedConsultConsult;
    private javax.swing.JLabel jLabelAdvancedConsultAuthor;
    private javax.swing.JLabel jLabelAdvancedConsultTitle;
    private javax.swing.JTextField jTextAdvancedConsultAuthor;
    private javax.swing.JTextField jTextAdvancedConsultTitle;
    // End of variables declaration//GEN-END:variables
}
