/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import categorias.Monografia;
import cruds.MonografiaCrud;
import java.util.List;
import javax.swing.DefaultListModel;
import persistenciaDados.CrudMonografiaObjects;

/**
 *
 * @author Lucas
 */
public class FrameMonografia extends javax.swing.JFrame {

    private List<String> displayList;

    /**
     * Creates new form FrameMonografia1
     */
    public FrameMonografia() {
        initComponents();

        jMonografiaTabbedPanel.setEnabledAt(1, false);
        jMonografiaTabbedPanel.setEnabledAt(2, false);
        jMonografiaTabbedPanel.setEnabledAt(3, false);

        jEditarMonografiaButton.setEnabled(false);
        jExcluirMonografiaButton.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMonografiaTabbedPanel = new javax.swing.JTabbedPane();
        jListarPanel = new javax.swing.JPanel();
        jMonografiaScrollPane = new javax.swing.JScrollPane();
        jMonografiaList = new javax.swing.JList<>();
        jAdicionarMonografiaButton = new javax.swing.JButton();
        jEditarMonografiaButton = new javax.swing.JButton();
        jExcluirMonografiaButton = new javax.swing.JButton();
        jVoltarMenuInicialButton = new javax.swing.JButton();
        jConsultaTextField = new javax.swing.JTextField();
        jConsultaLabel = new javax.swing.JLabel();
        jConsultaComboBox = new javax.swing.JComboBox<>();
        jConsultaButton = new javax.swing.JButton();
        jConsultaAvancadaButton = new javax.swing.JButton();
        jConsultarPane = new javax.swing.JPanel();
        jTituloLabel1 = new javax.swing.JLabel();
        jTituloTextField1 = new javax.swing.JTextField();
        jAutorLabel1 = new javax.swing.JLabel();
        jAutorTextField1 = new javax.swing.JTextField();
        jOrientadorLabel1 = new javax.swing.JLabel();
        jOrientadorTextField1 = new javax.swing.JTextField();
        jTipoComboBox1 = new javax.swing.JComboBox<>();
        jTipoLabel1 = new javax.swing.JLabel();
        jSituacaoLabel1 = new javax.swing.JLabel();
        jSituacaoComboBox1 = new javax.swing.JComboBox<>();
        jAnoTextField1 = new javax.swing.JTextField();
        jAnoLabel1 = new javax.swing.JLabel();
        jNPaginasLabel1 = new javax.swing.JLabel();
        jNPaginasTextField1 = new javax.swing.JTextField();
        jInstituicaoTextField1 = new javax.swing.JTextField();
        jInstituicaoLabel1 = new javax.swing.JLabel();
        jCursoTextField1 = new javax.swing.JTextField();
        jCursoLabel1 = new javax.swing.JLabel();
        jPalavrasChavesLabel1 = new javax.swing.JLabel();
        jPalavraChaveTextField5 = new javax.swing.JTextField();
        jPalavraChaveTextField6 = new javax.swing.JTextField();
        jPalavraChaveTextField7 = new javax.swing.JTextField();
        jPalavraChaveTextField8 = new javax.swing.JTextField();
        jSalvarButton1 = new javax.swing.JButton();
        jConsultaAvancadaVoltarButton = new javax.swing.JButton();
        jAdicionarPanel = new javax.swing.JPanel();
        jTituloLabel = new javax.swing.JLabel();
        jTituloTextField = new javax.swing.JTextField();
        jAutorLabel = new javax.swing.JLabel();
        jAutorTextField = new javax.swing.JTextField();
        jOrientadorLabel = new javax.swing.JLabel();
        jOrientadorTextField = new javax.swing.JTextField();
        jTipoComboBox = new javax.swing.JComboBox<>();
        jTipoLabel = new javax.swing.JLabel();
        jSituacaoLabel = new javax.swing.JLabel();
        jSituacaoComboBox = new javax.swing.JComboBox<>();
        jAnoTextField = new javax.swing.JTextField();
        jAnoLabel = new javax.swing.JLabel();
        jNPaginasLabel = new javax.swing.JLabel();
        jNPaginasTextField = new javax.swing.JTextField();
        jInstituicaoTextField = new javax.swing.JTextField();
        jInstituicaoLabel = new javax.swing.JLabel();
        jCursoTextField = new javax.swing.JTextField();
        jCursoLabel = new javax.swing.JLabel();
        jPalavrasChavesLabel = new javax.swing.JLabel();
        jPalavraChaveTextField0 = new javax.swing.JTextField();
        jPalavraChaveTextField1 = new javax.swing.JTextField();
        jPalavraChaveTextField2 = new javax.swing.JTextField();
        jPalavraChaveTextField3 = new javax.swing.JTextField();
        jAdicionarResumoButton = new javax.swing.JButton();
        jAdicionarAbstractButton = new javax.swing.JButton();
        jSalvarButton = new javax.swing.JButton();
        jCancelarButton = new javax.swing.JButton();
        jEditarPanel = new javax.swing.JPanel();
        jEditarTituloLabel = new javax.swing.JLabel();
        jEditarTituloTextField = new javax.swing.JTextField();
        jEditarAutorLabel = new javax.swing.JLabel();
        jEditarAutorTextField = new javax.swing.JTextField();
        jEditarOrientadorLabel = new javax.swing.JLabel();
        jEditarOrientadorTextField = new javax.swing.JTextField();
        jEditarTipoComboBox = new javax.swing.JComboBox<>();
        jEditarTipoLabel = new javax.swing.JLabel();
        jEditarSituacaoLabel = new javax.swing.JLabel();
        jEditarSituacaoComboBox = new javax.swing.JComboBox<>();
        jEditarAnoTextField = new javax.swing.JTextField();
        jEditarAnoLabel = new javax.swing.JLabel();
        jEditarNPaginasLabel = new javax.swing.JLabel();
        jEditarNPaginasTextField = new javax.swing.JTextField();
        jEditarInstituicaoTextField = new javax.swing.JTextField();
        jEditarInstituicaoLabel = new javax.swing.JLabel();
        jEditarCursoTextField = new javax.swing.JTextField();
        jEditarCursoLabel = new javax.swing.JLabel();
        jEditarPalvrasChaveLabel = new javax.swing.JLabel();
        jEditarPalavraChaveTextField0 = new javax.swing.JTextField();
        jEditarPalavraChaveTextField1 = new javax.swing.JTextField();
        jEditarPalavraChaveTextField2 = new javax.swing.JTextField();
        jEditarPalavraChaveTextField3 = new javax.swing.JTextField();
        jEditarResumoButton = new javax.swing.JButton();
        jEditarAbstractButton = new javax.swing.JButton();
        jEditarSalvarButton = new javax.swing.JButton();
        jEditarCanclearButton = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMonografiaTabbedPanel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jMonografiaTabbedPanelStateChanged(evt);
            }
        });

        jMonografiaList.setToolTipText("");
        jMonografiaList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jMonografiaListValueChanged(evt);
            }
        });
        jMonografiaScrollPane.setViewportView(jMonografiaList);

        jAdicionarMonografiaButton.setText("Nova");
        jAdicionarMonografiaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAdicionarMonografiaButtonActionPerformed(evt);
            }
        });

        jEditarMonografiaButton.setText("Editar");

        jExcluirMonografiaButton.setText("Excluir");
        jExcluirMonografiaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcluirMonografiaButtonActionPerformed(evt);
            }
        });

        jVoltarMenuInicialButton.setText("Voltar");
        jVoltarMenuInicialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVoltarMenuInicialButtonActionPerformed(evt);
            }
        });

        jConsultaLabel.setText("Consultar por:");

        jConsultaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Listar tudo", "Título", "Autor", "Orientador", "Curso" }));

        jConsultaButton.setText("Consultar");
        jConsultaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultaButtonActionPerformed(evt);
            }
        });

        jConsultaAvancadaButton.setText("Consulta Avançada");
        jConsultaAvancadaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultaAvancadaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jListarPanelLayout = new javax.swing.GroupLayout(jListarPanel);
        jListarPanel.setLayout(jListarPanelLayout);
        jListarPanelLayout.setHorizontalGroup(
            jListarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jListarPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jListarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jListarPanelLayout.createSequentialGroup()
                        .addComponent(jConsultaLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jConsultaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(jConsultaAvancadaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addComponent(jConsultaTextField)
                    .addGroup(jListarPanelLayout.createSequentialGroup()
                        .addGroup(jListarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jAdicionarMonografiaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jEditarMonografiaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jExcluirMonografiaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(jVoltarMenuInicialButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jMonografiaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jListarPanelLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jConsultaButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jListarPanelLayout.setVerticalGroup(
            jListarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jListarPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jListarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jConsultaLabel)
                    .addComponent(jConsultaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jConsultaAvancadaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jConsultaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jConsultaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jListarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jListarPanelLayout.createSequentialGroup()
                        .addComponent(jAdicionarMonografiaButton)
                        .addGap(27, 27, 27)
                        .addComponent(jEditarMonografiaButton)
                        .addGap(26, 26, 26)
                        .addComponent(jExcluirMonografiaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jVoltarMenuInicialButton))
                    .addComponent(jMonografiaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jMonografiaTabbedPanel.addTab("Monografias", jListarPanel);

        jTituloLabel1.setText("Título");

        jAutorLabel1.setText("Autor");

        jOrientadorLabel1.setText("Orientador");

        jTipoComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Graduação", "Especialização", "Mestrado", "Doutorado" }));

        jTipoLabel1.setText("Tipo");

        jSituacaoLabel1.setText("Situação");

        jSituacaoComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sob avaliação", "Aprovado", "Reprovado" }));
        jSituacaoComboBox1.setToolTipText("");

        jAnoLabel1.setText("Ano");

        jNPaginasLabel1.setText("Nº Páginas");

        jInstituicaoLabel1.setText("Instituição");

        jCursoLabel1.setText("Curso");

        jPalavrasChavesLabel1.setText("Palavras Chave");

        jSalvarButton1.setText("Pesquisar");
        jSalvarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalvarButton1ActionPerformed(evt);
            }
        });

        jConsultaAvancadaVoltarButton.setText("Voltar");

        javax.swing.GroupLayout jConsultarPaneLayout = new javax.swing.GroupLayout(jConsultarPane);
        jConsultarPane.setLayout(jConsultarPaneLayout);
        jConsultarPaneLayout.setHorizontalGroup(
            jConsultarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jConsultarPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jConsultarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jOrientadorTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTituloTextField1)
                    .addComponent(jAutorTextField1)
                    .addGroup(jConsultarPaneLayout.createSequentialGroup()
                        .addGroup(jConsultarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTituloLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAutorLabel1)
                            .addComponent(jOrientadorLabel1)
                            .addGroup(jConsultarPaneLayout.createSequentialGroup()
                                .addComponent(jTipoComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jSituacaoComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jAnoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jConsultarPaneLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jTipoLabel1)
                .addGap(111, 111, 111)
                .addComponent(jSituacaoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jAnoLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jNPaginasLabel1)
                .addGap(52, 52, 52))
            .addGroup(jConsultarPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCursoTextField1)
                .addContainerGap())
            .addGroup(jConsultarPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jConsultarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jConsultarPaneLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jCursoLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jConsultarPaneLayout.createSequentialGroup()
                        .addComponent(jInstituicaoTextField1)
                        .addContainerGap())))
            .addGroup(jConsultarPaneLayout.createSequentialGroup()
                .addGroup(jConsultarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jConsultarPaneLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jInstituicaoLabel1))
                    .addGroup(jConsultarPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jConsultarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPalavrasChavesLabel1)
                            .addGroup(jConsultarPaneLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jPalavraChaveTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPalavraChaveTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 24, Short.MAX_VALUE)
                                .addComponent(jPalavraChaveTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPalavraChaveTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jConsultarPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jConsultarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jConsultarPaneLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jNPaginasTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jConsultarPaneLayout.createSequentialGroup()
                        .addComponent(jConsultaAvancadaVoltarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSalvarButton1)
                        .addContainerGap())))
        );
        jConsultarPaneLayout.setVerticalGroup(
            jConsultarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jConsultarPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTituloLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTituloTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jAutorLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jAutorTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jOrientadorLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jOrientadorTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jConsultarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTipoLabel1)
                    .addComponent(jSituacaoLabel1)
                    .addComponent(jAnoLabel1)
                    .addComponent(jNPaginasLabel1))
                .addGap(7, 7, 7)
                .addGroup(jConsultarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTipoComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSituacaoComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAnoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNPaginasTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jInstituicaoLabel1)
                .addGap(10, 10, 10)
                .addComponent(jInstituicaoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCursoLabel1)
                .addGap(5, 5, 5)
                .addComponent(jCursoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPalavrasChavesLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jConsultarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPalavraChaveTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPalavraChaveTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPalavraChaveTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPalavraChaveTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jConsultarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSalvarButton1)
                    .addComponent(jConsultaAvancadaVoltarButton))
                .addContainerGap())
        );

        jMonografiaTabbedPanel.addTab("Consultar", jConsultarPane);

        jTituloLabel.setText("Título");

        jAutorLabel.setText("Autor");

        jOrientadorLabel.setText("Orientador");

        jTipoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Graduação", "Especialização", "Mestrado", "Doutorado" }));

        jTipoLabel.setText("Tipo");

        jSituacaoLabel.setText("Situação");

        jSituacaoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sob avaliação", "Aprovado", "Reprovado" }));
        jSituacaoComboBox.setToolTipText("");

        jAnoLabel.setText("Ano");

        jNPaginasLabel.setText("Nº Páginas");

        jInstituicaoLabel.setText("Instituição");

        jCursoLabel.setText("Curso");

        jPalavrasChavesLabel.setText("Palavras Chave");

        jAdicionarResumoButton.setText("Adicionar Resumo");

        jAdicionarAbstractButton.setText("Adicionar Abstract");

        jSalvarButton.setText("Salvar");
        jSalvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalvarButtonActionPerformed(evt);
            }
        });

        jCancelarButton.setText("Cancelar");

        javax.swing.GroupLayout jAdicionarPanelLayout = new javax.swing.GroupLayout(jAdicionarPanel);
        jAdicionarPanel.setLayout(jAdicionarPanelLayout);
        jAdicionarPanelLayout.setHorizontalGroup(
            jAdicionarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAdicionarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jAdicionarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jOrientadorTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTituloTextField)
                    .addComponent(jAutorTextField)
                    .addGroup(jAdicionarPanelLayout.createSequentialGroup()
                        .addGroup(jAdicionarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAutorLabel)
                            .addComponent(jOrientadorLabel)
                            .addGroup(jAdicionarPanelLayout.createSequentialGroup()
                                .addComponent(jTipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jSituacaoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jAnoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jAdicionarPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jTipoLabel)
                .addGap(111, 111, 111)
                .addComponent(jSituacaoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jAnoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jNPaginasLabel)
                .addGap(52, 52, 52))
            .addGroup(jAdicionarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCursoTextField)
                .addContainerGap())
            .addGroup(jAdicionarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jAdicionarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jAdicionarPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jCursoLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jAdicionarPanelLayout.createSequentialGroup()
                        .addComponent(jInstituicaoTextField)
                        .addContainerGap())))
            .addGroup(jAdicionarPanelLayout.createSequentialGroup()
                .addGroup(jAdicionarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jAdicionarPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jInstituicaoLabel))
                    .addGroup(jAdicionarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jAdicionarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPalavrasChavesLabel)
                            .addGroup(jAdicionarPanelLayout.createSequentialGroup()
                                .addGroup(jAdicionarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jAdicionarPanelLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jPalavraChaveTextField0, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPalavraChaveTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jAdicionarPanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jAdicionarResumoButton)
                                        .addGap(71, 71, 71)))
                                .addGroup(jAdicionarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jAdicionarPanelLayout.createSequentialGroup()
                                        .addComponent(jPalavraChaveTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPalavraChaveTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jAdicionarPanelLayout.createSequentialGroup()
                                        .addComponent(jAdicionarAbstractButton)
                                        .addGap(63, 63, 63)))))))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jAdicionarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jAdicionarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jAdicionarPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jNPaginasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jAdicionarPanelLayout.createSequentialGroup()
                        .addComponent(jCancelarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSalvarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jAdicionarPanelLayout.setVerticalGroup(
            jAdicionarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAdicionarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTituloLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTituloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jAutorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jAutorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jOrientadorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jOrientadorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jAdicionarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTipoLabel)
                    .addComponent(jSituacaoLabel)
                    .addComponent(jAnoLabel)
                    .addComponent(jNPaginasLabel))
                .addGap(7, 7, 7)
                .addGroup(jAdicionarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSituacaoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAnoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNPaginasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jInstituicaoLabel)
                .addGap(10, 10, 10)
                .addComponent(jInstituicaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCursoLabel)
                .addGap(5, 5, 5)
                .addComponent(jCursoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPalavrasChavesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jAdicionarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPalavraChaveTextField0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPalavraChaveTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPalavraChaveTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPalavraChaveTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jAdicionarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAdicionarResumoButton)
                    .addComponent(jAdicionarAbstractButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jAdicionarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSalvarButton)
                    .addComponent(jCancelarButton))
                .addContainerGap())
        );

        jMonografiaTabbedPanel.addTab("Adicionar", jAdicionarPanel);

        jEditarTituloLabel.setText("Título");

        jEditarAutorLabel.setText("Autor");

        jEditarOrientadorLabel.setText("Orientador");

        jEditarTipoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jEditarTipoLabel.setText("Tipo");

        jEditarSituacaoLabel.setText("Situação");

        jEditarSituacaoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jEditarAnoLabel.setText("Ano");

        jEditarNPaginasLabel.setText("Nº Páginas");

        jEditarInstituicaoLabel.setText("Instituição");

        jEditarCursoLabel.setText("Curso");

        jEditarPalvrasChaveLabel.setText("Palavras Chave");

        jEditarResumoButton.setText("Adicionar Resumo");

        jEditarAbstractButton.setText("Adicionar Abstract");

        jEditarSalvarButton.setText("Salvar");

        jEditarCanclearButton.setText("Cancelar");

        javax.swing.GroupLayout jEditarPanelLayout = new javax.swing.GroupLayout(jEditarPanel);
        jEditarPanel.setLayout(jEditarPanelLayout);
        jEditarPanelLayout.setHorizontalGroup(
            jEditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEditarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jEditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jEditarOrientadorTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jEditarTituloTextField)
                    .addComponent(jEditarAutorTextField)
                    .addGroup(jEditarPanelLayout.createSequentialGroup()
                        .addGroup(jEditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jEditarTituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEditarAutorLabel)
                            .addComponent(jEditarOrientadorLabel)
                            .addGroup(jEditarPanelLayout.createSequentialGroup()
                                .addComponent(jEditarTipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jEditarSituacaoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jEditarAnoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jEditarPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jEditarTipoLabel)
                .addGap(111, 111, 111)
                .addComponent(jEditarSituacaoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jEditarAnoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jEditarNPaginasLabel)
                .addGap(52, 52, 52))
            .addGroup(jEditarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jEditarCursoTextField)
                .addContainerGap())
            .addGroup(jEditarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jEditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jEditarPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jEditarCursoLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jEditarPanelLayout.createSequentialGroup()
                        .addComponent(jEditarInstituicaoTextField)
                        .addContainerGap())))
            .addGroup(jEditarPanelLayout.createSequentialGroup()
                .addGroup(jEditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jEditarPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jEditarInstituicaoLabel))
                    .addGroup(jEditarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jEditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jEditarPalvrasChaveLabel)
                            .addGroup(jEditarPanelLayout.createSequentialGroup()
                                .addGroup(jEditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jEditarPanelLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jEditarPalavraChaveTextField0, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jEditarPalavraChaveTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 25, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jEditarPanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jEditarResumoButton)
                                        .addGap(71, 71, 71)))
                                .addGroup(jEditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jEditarPanelLayout.createSequentialGroup()
                                        .addComponent(jEditarPalavraChaveTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jEditarPalavraChaveTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jEditarPanelLayout.createSequentialGroup()
                                        .addComponent(jEditarAbstractButton)
                                        .addGap(63, 63, 63)))))))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jEditarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jEditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jEditarPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jEditarNPaginasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jEditarPanelLayout.createSequentialGroup()
                        .addComponent(jEditarCanclearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jEditarSalvarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jEditarPanelLayout.setVerticalGroup(
            jEditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEditarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jEditarTituloLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jEditarTituloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jEditarAutorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jEditarAutorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jEditarOrientadorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jEditarOrientadorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jEditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEditarTipoLabel)
                    .addComponent(jEditarSituacaoLabel)
                    .addComponent(jEditarAnoLabel)
                    .addComponent(jEditarNPaginasLabel))
                .addGap(7, 7, 7)
                .addGroup(jEditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEditarTipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEditarSituacaoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEditarAnoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEditarNPaginasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jEditarInstituicaoLabel)
                .addGap(10, 10, 10)
                .addComponent(jEditarInstituicaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jEditarCursoLabel)
                .addGap(5, 5, 5)
                .addComponent(jEditarCursoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jEditarPalvrasChaveLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jEditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEditarPalavraChaveTextField0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEditarPalavraChaveTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEditarPalavraChaveTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEditarPalavraChaveTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jEditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEditarResumoButton)
                    .addComponent(jEditarAbstractButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jEditarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEditarSalvarButton)
                    .addComponent(jEditarCanclearButton))
                .addContainerGap())
        );

        jMonografiaTabbedPanel.addTab("Editar", jEditarPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jMonografiaTabbedPanel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMonografiaTabbedPanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSalvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalvarButtonActionPerformed

        Monografia monografia = new Monografia();

        monografia.setTitulo(jTituloTextField.getText());
        monografia.setAutor(jAutorTextField.getText());
        monografia.setOrientador(jOrientadorTextField.getText());
        monografia.setTipo(jTipoComboBox.getSelectedItem().toString());
        monografia.setSituacao(jSituacaoComboBox.getSelectedItem().toString());

        if (jAnoTextField.getText().isEmpty() == false) {
            monografia.setAno(Integer.valueOf(jAnoTextField.getText()));
        }

        if (jNPaginasTextField.getText().isEmpty() == false) {
            monografia.setNPaginas(Integer.valueOf(jNPaginasTextField.getText()));
        }

        monografia.setInstituicao(jInstituicaoTextField.getText());
        monografia.setCurso(jCursoTextField.getText());

        String[] palavrasChave = new String[4];

        palavrasChave[0] = jPalavraChaveTextField0.getText();
        palavrasChave[1] = jPalavraChaveTextField1.getText();
        palavrasChave[2] = jPalavraChaveTextField2.getText();
        palavrasChave[3] = jPalavraChaveTextField3.getText();

        monografia.setPalavraChave(palavrasChave);
        monografia.setAbstractText("sdsdfs");
        monografia.setResumo("sdfddaf");

        MonografiaCrud.adicionar(monografia);

        CrudMonografiaObjects.createObject(MonografiaCrud.getMonografiaList());

        jMonografiaTabbedPanel.setSelectedIndex(0);
        jMonografiaTabbedPanel.setEnabledAt(2, false);
        jMonografiaTabbedPanel.setEnabledAt(0, true);


    }//GEN-LAST:event_jSalvarButtonActionPerformed

    private void jMonografiaTabbedPanelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jMonografiaTabbedPanelStateChanged
        //if (jMonografiaTabbedPanel.getSelectedIndex() == 0) {
        //   MonografiaCrud.listar(jMonografiaList);
        // }
    }//GEN-LAST:event_jMonografiaTabbedPanelStateChanged

    private void jSalvarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalvarButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSalvarButton1ActionPerformed

    private void jConsultaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultaButtonActionPerformed
        
        
        MonografiaCrud.setMonografiaList(CrudMonografiaObjects.readObject("blablabla"));
        displayList = MonografiaCrud.consultar(jConsultaComboBox.getSelectedItem().toString(), jConsultaTextField.getText());
        listar();
        
    }//GEN-LAST:event_jConsultaButtonActionPerformed

    private void jAdicionarMonografiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdicionarMonografiaButtonActionPerformed
        jMonografiaTabbedPanel.setSelectedIndex(2);
        jMonografiaTabbedPanel.setEnabledAt(2, true);
        jMonografiaTabbedPanel.setEnabledAt(0, false);
    }//GEN-LAST:event_jAdicionarMonografiaButtonActionPerformed

    private void jMonografiaListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jMonografiaListValueChanged
        if (jMonografiaList.isSelectionEmpty() == false) {
            jEditarMonografiaButton.setEnabled(true);
            jExcluirMonografiaButton.setEnabled(true);
        } else {
            jEditarMonografiaButton.setEnabled(false);
            jExcluirMonografiaButton.setEnabled(false);
        }
    }//GEN-LAST:event_jMonografiaListValueChanged

    private void jExcluirMonografiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExcluirMonografiaButtonActionPerformed

        MonografiaCrud.excluir(jMonografiaList.getSelectedValue());
        displayList = MonografiaCrud.consultar("", "");
        listar();

    }//GEN-LAST:event_jExcluirMonografiaButtonActionPerformed

    private void jConsultaAvancadaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultaAvancadaButtonActionPerformed
        jMonografiaTabbedPanel.setSelectedIndex(1);
        jMonografiaTabbedPanel.setEnabledAt(1, true);
        jMonografiaTabbedPanel.setEnabledAt(0, false);
    }//GEN-LAST:event_jConsultaAvancadaButtonActionPerformed

    private void jVoltarMenuInicialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVoltarMenuInicialButtonActionPerformed
        new Inicial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jVoltarMenuInicialButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMonografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMonografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMonografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMonografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMonografia().setVisible(true);
            }
        });
    }

    private void listar() {

        DefaultListModel listModel = new DefaultListModel();

        for (String element : displayList) {
            listModel.addElement(element);
        }

        jMonografiaList.setModel(listModel);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAdicionarAbstractButton;
    private javax.swing.JButton jAdicionarMonografiaButton;
    private javax.swing.JPanel jAdicionarPanel;
    private javax.swing.JButton jAdicionarResumoButton;
    private javax.swing.JLabel jAnoLabel;
    private javax.swing.JLabel jAnoLabel1;
    private javax.swing.JTextField jAnoTextField;
    private javax.swing.JTextField jAnoTextField1;
    private javax.swing.JLabel jAutorLabel;
    private javax.swing.JLabel jAutorLabel1;
    private javax.swing.JTextField jAutorTextField;
    private javax.swing.JTextField jAutorTextField1;
    private javax.swing.JButton jCancelarButton;
    private javax.swing.JButton jConsultaAvancadaButton;
    private javax.swing.JButton jConsultaAvancadaVoltarButton;
    private javax.swing.JButton jConsultaButton;
    private javax.swing.JComboBox<String> jConsultaComboBox;
    private javax.swing.JLabel jConsultaLabel;
    private javax.swing.JTextField jConsultaTextField;
    private javax.swing.JPanel jConsultarPane;
    private javax.swing.JLabel jCursoLabel;
    private javax.swing.JLabel jCursoLabel1;
    private javax.swing.JTextField jCursoTextField;
    private javax.swing.JTextField jCursoTextField1;
    private javax.swing.JButton jEditarAbstractButton;
    private javax.swing.JLabel jEditarAnoLabel;
    private javax.swing.JTextField jEditarAnoTextField;
    private javax.swing.JLabel jEditarAutorLabel;
    private javax.swing.JTextField jEditarAutorTextField;
    private javax.swing.JButton jEditarCanclearButton;
    private javax.swing.JLabel jEditarCursoLabel;
    private javax.swing.JTextField jEditarCursoTextField;
    private javax.swing.JLabel jEditarInstituicaoLabel;
    private javax.swing.JTextField jEditarInstituicaoTextField;
    private javax.swing.JButton jEditarMonografiaButton;
    private javax.swing.JLabel jEditarNPaginasLabel;
    private javax.swing.JTextField jEditarNPaginasTextField;
    private javax.swing.JLabel jEditarOrientadorLabel;
    private javax.swing.JTextField jEditarOrientadorTextField;
    private javax.swing.JTextField jEditarPalavraChaveTextField0;
    private javax.swing.JTextField jEditarPalavraChaveTextField1;
    private javax.swing.JTextField jEditarPalavraChaveTextField2;
    private javax.swing.JTextField jEditarPalavraChaveTextField3;
    private javax.swing.JLabel jEditarPalvrasChaveLabel;
    private javax.swing.JPanel jEditarPanel;
    private javax.swing.JButton jEditarResumoButton;
    private javax.swing.JButton jEditarSalvarButton;
    private javax.swing.JComboBox<String> jEditarSituacaoComboBox;
    private javax.swing.JLabel jEditarSituacaoLabel;
    private javax.swing.JComboBox<String> jEditarTipoComboBox;
    private javax.swing.JLabel jEditarTipoLabel;
    private javax.swing.JLabel jEditarTituloLabel;
    private javax.swing.JTextField jEditarTituloTextField;
    private javax.swing.JButton jExcluirMonografiaButton;
    private javax.swing.JLabel jInstituicaoLabel;
    private javax.swing.JLabel jInstituicaoLabel1;
    private javax.swing.JTextField jInstituicaoTextField;
    private javax.swing.JTextField jInstituicaoTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jListarPanel;
    private javax.swing.JList<String> jMonografiaList;
    private javax.swing.JScrollPane jMonografiaScrollPane;
    private javax.swing.JTabbedPane jMonografiaTabbedPanel;
    private javax.swing.JLabel jNPaginasLabel;
    private javax.swing.JLabel jNPaginasLabel1;
    private javax.swing.JTextField jNPaginasTextField;
    private javax.swing.JTextField jNPaginasTextField1;
    private javax.swing.JLabel jOrientadorLabel;
    private javax.swing.JLabel jOrientadorLabel1;
    private javax.swing.JTextField jOrientadorTextField;
    private javax.swing.JTextField jOrientadorTextField1;
    private javax.swing.JTextField jPalavraChaveTextField0;
    private javax.swing.JTextField jPalavraChaveTextField1;
    private javax.swing.JTextField jPalavraChaveTextField2;
    private javax.swing.JTextField jPalavraChaveTextField3;
    private javax.swing.JTextField jPalavraChaveTextField5;
    private javax.swing.JTextField jPalavraChaveTextField6;
    private javax.swing.JTextField jPalavraChaveTextField7;
    private javax.swing.JTextField jPalavraChaveTextField8;
    private javax.swing.JLabel jPalavrasChavesLabel;
    private javax.swing.JLabel jPalavrasChavesLabel1;
    private javax.swing.JButton jSalvarButton;
    private javax.swing.JButton jSalvarButton1;
    private javax.swing.JComboBox<String> jSituacaoComboBox;
    private javax.swing.JComboBox<String> jSituacaoComboBox1;
    private javax.swing.JLabel jSituacaoLabel;
    private javax.swing.JLabel jSituacaoLabel1;
    private javax.swing.JComboBox<String> jTipoComboBox;
    private javax.swing.JComboBox<String> jTipoComboBox1;
    private javax.swing.JLabel jTipoLabel;
    private javax.swing.JLabel jTipoLabel1;
    private javax.swing.JLabel jTituloLabel;
    private javax.swing.JLabel jTituloLabel1;
    private javax.swing.JTextField jTituloTextField;
    private javax.swing.JTextField jTituloTextField1;
    private javax.swing.JButton jVoltarMenuInicialButton;
    // End of variables declaration//GEN-END:variables
}
