/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import categorias.Minicurso;
import cruds.MinicursoCRUD;
import java.util.List;

/**
 *
 * @author YuryAlencar
 */
public class FrameMinicursoDetalhes extends javax.swing.JFrame {

    List<Minicurso> minicursos = MinicursoCRUD.getMinicursos();
    /**
     * Creates new form MoreDetailsShortCourse
     */
    public FrameMinicursoDetalhes(String titleDetails) {
        initComponents();
        this.setTitle("RP II - Detalhes");
        this.setLocationRelativeTo(null);
        
        String indexNumberAuthors = "", duracaoEditar;
        int hora, minutos, segundos;
        
        for(Minicurso minicurso : minicursos){
            if(minicurso.getTituloSubmissao().equals(titleDetails)){
                
                hora = minicurso.getDuracao()/3600;
                minutos = (minicurso.getDuracao()%3600)/60;
                segundos = (minicurso.getDuracao()%3600)%60;
                
                if(segundos<10 && hora<10 && minutos <10)
                    duracaoEditar = "0"+String.valueOf(hora)+"0"+String.valueOf(minutos)
                            +"0"+String.valueOf(segundos);
                else if(segundos<10 && hora<10)
                    duracaoEditar = "0"+String.valueOf(hora)+String.valueOf(minutos)
                            +"0"+String.valueOf(segundos);
                else if(segundos<10 && minutos<10)
                    duracaoEditar = String.valueOf(hora)+"0"+String.valueOf(minutos)
                            +"0"+String.valueOf(segundos);
                else if(hora<10 && minutos<10)
                    duracaoEditar = "0"+String.valueOf(hora)+"0"+String.valueOf(minutos)
                            +String.valueOf(segundos);
                else
                    duracaoEditar = String.valueOf(hora)+String.valueOf(minutos)
                            +String.valueOf(segundos);
                
                
                jTextMaisDetalhesTitulo.setText(minicurso.getTituloSubmissao());
                jTextMaisDetalhesSituacao.setText(minicurso.getSituacaoSubmissao().toString());
                jTextPaneMaisDetalhesResumoTexto.setText(minicurso.getResumo());
                jTextPaneMaisDetalhesAbstractTexto.setText(minicurso.getAbstractText());
                jFormattedTextMaisDetalhesDuracao.setText(duracaoEditar);
                jTextPaneMaisDetalhesMetodologia.setText(minicurso.getMetodologia());
                jTextMaisDetalhesRecursos.setText(minicurso.getRecursos());
                if(minicurso.getAutores().size() == 1){
                    jTextMaisDetalhesAutor.setText(minicurso.getAutores().get(0));
                    indexNumberAuthors = "1";
                } else if (minicurso.getAutores().size() == 2){
                    jTextMaisDetalhesAutor.setText(minicurso.getAutores().get(0));
                    jTextMaisDetalhesAutor1.setText(minicurso.getAutores().get(1));
                    indexNumberAuthors = "2";
                } else if(minicurso.getAutores().size() == 3){
                    jTextMaisDetalhesAutor.setText(minicurso.getAutores().get(0));
                    jTextMaisDetalhesAutor1.setText(minicurso.getAutores().get(1));
                    jTextMaisDetalhesAutor2.setText(minicurso.getAutores().get(2));
                    indexNumberAuthors = "3";
                }
                jTextMaisDetalhesNumeroAutores.setText(indexNumberAuthors);
                
            }
        }
        
        jTextMaisDetalhesTitulo.setEnabled(false);
        jTextMaisDetalhesSituacao.setEnabled(false);
        jTextPaneMaisDetalhesResumoTexto.setEnabled(false);
        jTextPaneMaisDetalhesAbstractTexto.setEnabled(false);
        jFormattedTextMaisDetalhesDuracao.setEnabled(false);
        jTextMaisDetalhesNumeroAutores.setEnabled(false);
        jTextPaneMaisDetalhesMetodologia.setEnabled(false);
        jTextMaisDetalhesRecursos.setEnabled(false);
        jTextMaisDetalhesAutor.setEnabled(false);
        jTextMaisDetalhesAutor1.setEnabled(false);
        jTextMaisDetalhesAutor2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMaisDetalhes = new javax.swing.JPanel();
        jLabelMaisDetalhesTitulo = new javax.swing.JLabel();
        jTextMaisDetalhesTitulo = new javax.swing.JTextField();
        jLabelMaisDetalhesSituacao = new javax.swing.JLabel();
        jLabelMaisDetalhesResumoTexto = new javax.swing.JLabel();
        jScrollPaneMaisDetalhesAbstractTexto = new javax.swing.JScrollPane();
        jTextPaneMaisDetalhesAbstractTexto = new javax.swing.JTextPane();
        jScrollPaneMaisDetalhesResumoTexto = new javax.swing.JScrollPane();
        jTextPaneMaisDetalhesResumoTexto = new javax.swing.JTextPane();
        jLabelMaisDetalhesAbstractTexto = new javax.swing.JLabel();
        jLabelMaisDetalhesDuracao = new javax.swing.JLabel();
        jFormattedTextMaisDetalhesDuracao = new javax.swing.JFormattedTextField();
        jLabelMaisDetalhesRecursos = new javax.swing.JLabel();
        jTextMaisDetalhesRecursos = new javax.swing.JTextField();
        jLabelMaisDetalhesMetodologia = new javax.swing.JLabel();
        jScrollPaneMaisDetalhesMetodologia = new javax.swing.JScrollPane();
        jTextPaneMaisDetalhesMetodologia = new javax.swing.JTextPane();
        jLabelMaisDetalhesAutor = new javax.swing.JLabel();
        jTextMaisDetalhesAutor = new javax.swing.JTextField();
        jTextMaisDetalhesAutor1 = new javax.swing.JTextField();
        jTextMaisDetalhesAutor2 = new javax.swing.JTextField();
        jButtonMaisDetalhesVoltar = new javax.swing.JButton();
        jTextMaisDetalhesSituacao = new javax.swing.JTextField();
        jTextMaisDetalhesNumeroAutores = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelMaisDetalhesTitulo.setText("Título: ");

        jTextMaisDetalhesTitulo.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabelMaisDetalhesSituacao.setText("Situação:");

        jLabelMaisDetalhesResumoTexto.setText("Resumo:");

        jTextPaneMaisDetalhesAbstractTexto.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPaneMaisDetalhesAbstractTexto.setViewportView(jTextPaneMaisDetalhesAbstractTexto);

        jTextPaneMaisDetalhesResumoTexto.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPaneMaisDetalhesResumoTexto.setViewportView(jTextPaneMaisDetalhesResumoTexto);

        jLabelMaisDetalhesAbstractTexto.setText("Abstract:");

        jLabelMaisDetalhesDuracao.setText("Duração:");

        try {
            jFormattedTextMaisDetalhesDuracao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextMaisDetalhesDuracao.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabelMaisDetalhesRecursos.setText("Recursos:");

        jTextMaisDetalhesRecursos.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabelMaisDetalhesMetodologia.setText("Metodologia:");

        jTextPaneMaisDetalhesMetodologia.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPaneMaisDetalhesMetodologia.setViewportView(jTextPaneMaisDetalhesMetodologia);

        jLabelMaisDetalhesAutor.setText("Autor:");

        jTextMaisDetalhesAutor.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jTextMaisDetalhesAutor1.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jTextMaisDetalhesAutor2.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jButtonMaisDetalhesVoltar.setText("Voltar");
        jButtonMaisDetalhesVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMaisDetalhesVoltarActionPerformed(evt);
            }
        });

        jTextMaisDetalhesSituacao.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jTextMaisDetalhesNumeroAutores.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanelMaisDetalhesLayout = new javax.swing.GroupLayout(jPanelMaisDetalhes);
        jPanelMaisDetalhes.setLayout(jPanelMaisDetalhesLayout);
        jPanelMaisDetalhesLayout.setHorizontalGroup(
            jPanelMaisDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMaisDetalhesLayout.createSequentialGroup()
                .addGroup(jPanelMaisDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMaisDetalhesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelMaisDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelMaisDetalhesLayout.createSequentialGroup()
                                .addGroup(jPanelMaisDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelMaisDetalhesLayout.createSequentialGroup()
                                        .addComponent(jLabelMaisDetalhesTitulo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextMaisDetalhesTitulo))
                                    .addGroup(jPanelMaisDetalhesLayout.createSequentialGroup()
                                        .addGroup(jPanelMaisDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelMaisDetalhesResumoTexto)
                                            .addComponent(jLabelMaisDetalhesSituacao))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanelMaisDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPaneMaisDetalhesResumoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanelMaisDetalhesLayout.createSequentialGroup()
                                                .addComponent(jTextMaisDetalhesSituacao)
                                                .addGap(1, 1, 1)))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelMaisDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelMaisDetalhesLayout.createSequentialGroup()
                                        .addComponent(jLabelMaisDetalhesDuracao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextMaisDetalhesDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelMaisDetalhesLayout.createSequentialGroup()
                                        .addComponent(jLabelMaisDetalhesRecursos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextMaisDetalhesRecursos, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelMaisDetalhesLayout.createSequentialGroup()
                                        .addComponent(jLabelMaisDetalhesMetodologia)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPaneMaisDetalhesMetodologia, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanelMaisDetalhesLayout.createSequentialGroup()
                                .addComponent(jLabelMaisDetalhesAbstractTexto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPaneMaisDetalhesAbstractTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelMaisDetalhesAutor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelMaisDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelMaisDetalhesLayout.createSequentialGroup()
                                        .addComponent(jTextMaisDetalhesAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextMaisDetalhesNumeroAutores))
                                    .addComponent(jTextMaisDetalhesAutor1)
                                    .addComponent(jTextMaisDetalhesAutor2)))))
                    .addGroup(jPanelMaisDetalhesLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jButtonMaisDetalhesVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        jPanelMaisDetalhesLayout.setVerticalGroup(
            jPanelMaisDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMaisDetalhesLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelMaisDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMaisDetalhesTitulo)
                    .addComponent(jTextMaisDetalhesTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMaisDetalhesDuracao)
                    .addComponent(jFormattedTextMaisDetalhesDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMaisDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMaisDetalhesSituacao)
                    .addComponent(jLabelMaisDetalhesRecursos)
                    .addComponent(jTextMaisDetalhesRecursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextMaisDetalhesSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMaisDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelMaisDetalhesResumoTexto)
                    .addComponent(jLabelMaisDetalhesMetodologia)
                    .addComponent(jScrollPaneMaisDetalhesMetodologia, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPaneMaisDetalhesResumoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanelMaisDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelMaisDetalhesAbstractTexto)
                    .addGroup(jPanelMaisDetalhesLayout.createSequentialGroup()
                        .addGroup(jPanelMaisDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMaisDetalhesAutor)
                            .addComponent(jTextMaisDetalhesAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextMaisDetalhesNumeroAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jTextMaisDetalhesAutor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextMaisDetalhesAutor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneMaisDetalhesAbstractTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jButtonMaisDetalhesVoltar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMaisDetalhes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMaisDetalhes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMaisDetalhesVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMaisDetalhesVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonMaisDetalhesVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMinicursoDetalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMinicursoDetalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMinicursoDetalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMinicursoDetalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMinicursoDetalhes(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMaisDetalhesVoltar;
    private javax.swing.JFormattedTextField jFormattedTextMaisDetalhesDuracao;
    private javax.swing.JLabel jLabelMaisDetalhesAbstractTexto;
    private javax.swing.JLabel jLabelMaisDetalhesAutor;
    private javax.swing.JLabel jLabelMaisDetalhesDuracao;
    private javax.swing.JLabel jLabelMaisDetalhesMetodologia;
    private javax.swing.JLabel jLabelMaisDetalhesRecursos;
    private javax.swing.JLabel jLabelMaisDetalhesResumoTexto;
    private javax.swing.JLabel jLabelMaisDetalhesSituacao;
    private javax.swing.JLabel jLabelMaisDetalhesTitulo;
    private javax.swing.JPanel jPanelMaisDetalhes;
    private javax.swing.JScrollPane jScrollPaneMaisDetalhesAbstractTexto;
    private javax.swing.JScrollPane jScrollPaneMaisDetalhesMetodologia;
    private javax.swing.JScrollPane jScrollPaneMaisDetalhesResumoTexto;
    private javax.swing.JTextField jTextMaisDetalhesAutor;
    private javax.swing.JTextField jTextMaisDetalhesAutor1;
    private javax.swing.JTextField jTextMaisDetalhesAutor2;
    private javax.swing.JTextField jTextMaisDetalhesNumeroAutores;
    private javax.swing.JTextField jTextMaisDetalhesRecursos;
    private javax.swing.JTextField jTextMaisDetalhesSituacao;
    private javax.swing.JTextField jTextMaisDetalhesTitulo;
    private javax.swing.JTextPane jTextPaneMaisDetalhesAbstractTexto;
    private javax.swing.JTextPane jTextPaneMaisDetalhesMetodologia;
    private javax.swing.JTextPane jTextPaneMaisDetalhesResumoTexto;
    // End of variables declaration//GEN-END:variables
}
