/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import cruds.MonografiaCrud;
import java.util.List;
import javax.swing.DefaultListModel;
import persistenciaDados.CrudMonografiaObjects;

/**
 *
 * @author Lucas
 */
public class FrameMonografia extends javax.swing.JFrame {

    private List<String> displayList;

    /**
     * Creates new form FrameMonografia1
     */
    public FrameMonografia() {
        initComponents();

        jTabbedPaneMonografia.setEnabledAt(1, false);
        jTabbedPaneMonografia.setEnabledAt(2, false);

        jButtonEditarMonografia.setEnabled(false);
        jButtonExcluirMonografia.setEnabled(false);

        MonografiaCrud.setMonografiaList(CrudMonografiaObjects.readObject("Monografias"));

        displayList = MonografiaCrud.consultar("", "");

        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneMonografia = new javax.swing.JTabbedPane();
        jPanelListar = new javax.swing.JPanel();
        jScrollPaneMonografias = new javax.swing.JScrollPane();
        jListMonografia = new javax.swing.JList<>();
        jButtonAdicionarMonografia = new javax.swing.JButton();
        jButtonEditarMonografia = new javax.swing.JButton();
        jButtonExcluirMonografia = new javax.swing.JButton();
        jlButtonVoltarMenuInicia = new javax.swing.JButton();
        jTextFieldConsulta = new javax.swing.JTextField();
        jLabelConsulta = new javax.swing.JLabel();
        jComboBoxConsulta = new javax.swing.JComboBox<>();
        jButtonConsulta = new javax.swing.JButton();
        jButtonConsultaAvancada = new javax.swing.JButton();
        jPanelAdicionar = new javax.swing.JPanel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jTextFieldAutor = new javax.swing.JTextField();
        jLabelAutor = new javax.swing.JLabel();
        jLabelOrientador = new javax.swing.JLabel();
        jTextFieldOrientador = new javax.swing.JTextField();
        jLabelTipo = new javax.swing.JLabel();
        jLabelSituacao = new javax.swing.JLabel();
        jLabelnPaginas = new javax.swing.JLabel();
        jLabelAno = new javax.swing.JLabel();
        jTextFieldAno = new javax.swing.JTextField();
        jTextFieldnPaginas = new javax.swing.JTextField();
        jComboBoxSituacao = new javax.swing.JComboBox<>();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jTextFieldInstituicao = new javax.swing.JTextField();
        jLabelCurso = new javax.swing.JLabel();
        jLabelInstituicao = new javax.swing.JLabel();
        jTextFieldCruso = new javax.swing.JTextField();
        jLabelPalavrasChaves = new javax.swing.JLabel();
        jTextFieldPalavraChave0 = new javax.swing.JTextField();
        jTextFieldPalavraChave1 = new javax.swing.JTextField();
        jTextFieldPalavraChave2 = new javax.swing.JTextField();
        jTextFieldPalavraChave3 = new javax.swing.JTextField();
        jLabelResumo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneAbstractText = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPaneResumo = new javax.swing.JTextPane();
        jLabelAbstractText = new javax.swing.JLabel();
        jPanelEditar = new javax.swing.JPanel();
        jSalvarButton1 = new javax.swing.JButton();
        jCancelarButton1 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jPanelEditar1 = new javax.swing.JPanel();
        jLabelTituloEditar = new javax.swing.JLabel();
        jTextFieldTituloEditar = new javax.swing.JTextField();
        jTextFieldAutorEditar = new javax.swing.JTextField();
        jLabelAutorEditar = new javax.swing.JLabel();
        jLabelOrientadorEditar = new javax.swing.JLabel();
        jTextFieldOrientadorEditar = new javax.swing.JTextField();
        jLabelTipoEditar = new javax.swing.JLabel();
        jLabelSituacaoEditar = new javax.swing.JLabel();
        jLabelnPaginasEditar = new javax.swing.JLabel();
        jLabelAnoEditar = new javax.swing.JLabel();
        jTextFieldAnoEditar = new javax.swing.JTextField();
        jTextFieldnPaginasEditar = new javax.swing.JTextField();
        jComboBoxSituacaoEditar = new javax.swing.JComboBox<>();
        jComboBoxTipoEditar = new javax.swing.JComboBox<>();
        jTextFieldInstituicaoEditar = new javax.swing.JTextField();
        jLabelCursoEditar = new javax.swing.JLabel();
        jLabelInstituicaoEditar = new javax.swing.JLabel();
        jTextFieldCrusoEditar = new javax.swing.JTextField();
        jLabelPalavrasChavesEditar = new javax.swing.JLabel();
        jTextFieldPalavraChaveEditar0 = new javax.swing.JTextField();
        jTextFieldPalavraChaveEditar1 = new javax.swing.JTextField();
        jTextFieldPalavraChaveEditar2 = new javax.swing.JTextField();
        jTextFieldPalavraChaveEditar3 = new javax.swing.JTextField();
        jLabelResumoEditar = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPaneAbstractTextEditar = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextPaneResumoEditar = new javax.swing.JTextPane();
        jLabelAbstractTextEditar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPaneMonografia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPaneMonografiaStateChanged(evt);
            }
        });

        jListMonografia.setToolTipText("");
        jListMonografia.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListMonografiaValueChanged(evt);
            }
        });
        jScrollPaneMonografias.setViewportView(jListMonografia);

        jButtonAdicionarMonografia.setText("Adicionar");
        jButtonAdicionarMonografia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarMonografiaActionPerformed(evt);
            }
        });

        jButtonEditarMonografia.setText("Editar");
        jButtonEditarMonografia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarMonografiaActionPerformed(evt);
            }
        });

        jButtonExcluirMonografia.setText("Excluir");
        jButtonExcluirMonografia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirMonografiaActionPerformed(evt);
            }
        });

        jlButtonVoltarMenuInicia.setText("Voltar");
        jlButtonVoltarMenuInicia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlButtonVoltarMenuIniciaActionPerformed(evt);
            }
        });

        jLabelConsulta.setText("Consultar por:");

        jComboBoxConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Listar tudo", "Título", "Autor", "Orientador", "Curso" }));

        jButtonConsulta.setText("Consultar");
        jButtonConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaActionPerformed(evt);
            }
        });

        jButtonConsultaAvancada.setText("Consulta Avançada");
        jButtonConsultaAvancada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaAvancadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelListarLayout = new javax.swing.GroupLayout(jPanelListar);
        jPanelListar.setLayout(jPanelListarLayout);
        jPanelListarLayout.setHorizontalGroup(
            jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldConsulta)
                    .addGroup(jPanelListarLayout.createSequentialGroup()
                        .addComponent(jLabelConsulta)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addComponent(jButtonConsultaAvancada, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelListarLayout.createSequentialGroup()
                        .addGroup(jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonEditarMonografia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAdicionarMonografia, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(jButtonExcluirMonografia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlButtonVoltarMenuInicia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPaneMonografias)))
                .addContainerGap())
            .addGroup(jPanelListarLayout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jButtonConsulta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelListarLayout.setVerticalGroup(
            jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConsultaAvancada)
                    .addComponent(jComboBoxConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelConsulta))
                .addGap(10, 10, 10)
                .addComponent(jTextFieldConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonConsulta)
                .addGap(26, 26, 26)
                .addGroup(jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelListarLayout.createSequentialGroup()
                        .addComponent(jButtonAdicionarMonografia)
                        .addGap(29, 29, 29)
                        .addComponent(jButtonEditarMonografia)
                        .addGap(36, 36, 36)
                        .addComponent(jButtonExcluirMonografia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlButtonVoltarMenuInicia))
                    .addComponent(jScrollPaneMonografias, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPaneMonografia.addTab("Monografias", jPanelListar);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jLabelTitulo.setText("Título");

        jLabelAutor.setText("Autor");

        jLabelOrientador.setText("Orientador");

        jLabelTipo.setText("Tipo");

        jLabelSituacao.setText("Situação");

        jLabelnPaginas.setText("Nº Páginas");

        jLabelAno.setText("Ano");

        jComboBoxSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sob avaliação", "Aprovado", "Reprovado" }));
        jComboBoxSituacao.setToolTipText("");

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Graduação", "Especialização", "Mestrado", "Doutorado" }));

        jLabelCurso.setText("Curso");

        jLabelInstituicao.setText("Instituição");

        jTextFieldCruso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCrusoActionPerformed(evt);
            }
        });

        jLabelPalavrasChaves.setText("Palavras Chave");

        jLabelResumo.setText("Resumo");

        jScrollPane2.setViewportView(jTextPaneAbstractText);

        jScrollPane3.setViewportView(jTextPaneResumo);

        jLabelAbstractText.setText("Abstract");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCruso, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                            .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAutor)
                            .addComponent(jLabelOrientador)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelInstituicao)
                                    .addComponent(jLabelCurso)))
                            .addComponent(jTextFieldInstituicao)
                            .addComponent(jTextFieldAutor)
                            .addComponent(jTextFieldTitulo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(204, 204, 204)
                                .addComponent(jLabelPalavrasChaves))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldPalavraChave0, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(jTextFieldPalavraChave1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane3))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldPalavraChave2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(jTextFieldPalavraChave3))
                                    .addComponent(jScrollPane2))))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabelTipo)
                        .addGap(127, 127, 127)
                        .addComponent(jLabelSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jLabelAno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelnPaginas)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldOrientador, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jComboBoxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jTextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jTextFieldnPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabelResumo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelAbstractText)
                .addGap(139, 139, 139))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldPalavraChave0, jTextFieldPalavraChave1, jTextFieldPalavraChave2});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldAutor, jTextFieldCruso, jTextFieldInstituicao, jTextFieldTitulo});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBoxSituacao, jComboBoxTipo});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldAno, jTextFieldnPaginas});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelOrientador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldOrientador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipo)
                    .addComponent(jLabelSituacao)
                    .addComponent(jLabelAno)
                    .addComponent(jLabelnPaginas))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldnPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelInstituicao)
                .addGap(10, 10, 10)
                .addComponent(jTextFieldInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCurso)
                .addGap(5, 5, 5)
                .addComponent(jTextFieldCruso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelPalavrasChaves)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPalavraChave0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPalavraChave2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPalavraChave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPalavraChave3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelResumo)
                    .addComponent(jLabelAbstractText))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextFieldPalavraChave0, jTextFieldPalavraChave1, jTextFieldPalavraChave2, jTextFieldPalavraChave3});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBoxSituacao, jComboBoxTipo});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane2, jScrollPane3});

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout jPanelAdicionarLayout = new javax.swing.GroupLayout(jPanelAdicionar);
        jPanelAdicionar.setLayout(jPanelAdicionarLayout);
        jPanelAdicionarLayout.setHorizontalGroup(
            jPanelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdicionarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButtonCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jPanelAdicionarLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelAdicionarLayout.setVerticalGroup(
            jPanelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdicionarLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonSalvar))
                .addGap(23, 23, 23))
        );

        jTabbedPaneMonografia.addTab("Adicionar", jPanelAdicionar);

        jSalvarButton1.setText("Salvar");
        jSalvarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalvarButton1ActionPerformed(evt);
            }
        });

        jCancelarButton1.setText("Cancelar");

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jLabelTituloEditar.setText("Título");

        jLabelAutorEditar.setText("Autor");

        jLabelOrientadorEditar.setText("Orientador");

        jLabelTipoEditar.setText("Tipo");

        jLabelSituacaoEditar.setText("Situação");

        jLabelnPaginasEditar.setText("Nº Páginas");

        jLabelAnoEditar.setText("Ano");

        jComboBoxSituacaoEditar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sob avaliação", "Aprovado", "Reprovado" }));
        jComboBoxSituacaoEditar.setToolTipText("");

        jComboBoxTipoEditar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Graduação", "Especialização", "Mestrado", "Doutorado" }));

        jLabelCursoEditar.setText("Curso");

        jLabelInstituicaoEditar.setText("Instituição");

        jTextFieldCrusoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCrusoEditarActionPerformed(evt);
            }
        });

        jLabelPalavrasChavesEditar.setText("Palavras Chave");

        jLabelResumoEditar.setText("Resumo");

        jScrollPane7.setViewportView(jTextPaneAbstractTextEditar);

        jScrollPane8.setViewportView(jTextPaneResumoEditar);

        jLabelAbstractTextEditar.setText("Abstract");

        javax.swing.GroupLayout jPanelEditar1Layout = new javax.swing.GroupLayout(jPanelEditar1);
        jPanelEditar1.setLayout(jPanelEditar1Layout);
        jPanelEditar1Layout.setHorizontalGroup(
            jPanelEditar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditar1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelEditar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelEditar1Layout.createSequentialGroup()
                        .addGroup(jPanelEditar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCrusoEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                            .addComponent(jLabelTituloEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAutorEditar)
                            .addComponent(jLabelOrientadorEditar)
                            .addGroup(jPanelEditar1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanelEditar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelInstituicaoEditar)
                                    .addComponent(jLabelCursoEditar)))
                            .addComponent(jTextFieldInstituicaoEditar)
                            .addComponent(jTextFieldAutorEditar)
                            .addComponent(jTextFieldTituloEditar)
                            .addGroup(jPanelEditar1Layout.createSequentialGroup()
                                .addGap(204, 204, 204)
                                .addComponent(jLabelPalavrasChavesEditar))
                            .addGroup(jPanelEditar1Layout.createSequentialGroup()
                                .addGroup(jPanelEditar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelEditar1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldPalavraChaveEditar0, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(jTextFieldPalavraChaveEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane8))
                                .addGap(20, 20, 20)
                                .addGroup(jPanelEditar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelEditar1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldPalavraChaveEditar2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(jTextFieldPalavraChaveEditar3))
                                    .addComponent(jScrollPane7))))
                        .addGap(20, 20, 20))
                    .addGroup(jPanelEditar1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabelTipoEditar)
                        .addGap(127, 127, 127)
                        .addComponent(jLabelSituacaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jLabelAnoEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelnPaginasEditar)
                        .addGap(32, 32, 32))
                    .addGroup(jPanelEditar1Layout.createSequentialGroup()
                        .addGroup(jPanelEditar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldOrientadorEditar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEditar1Layout.createSequentialGroup()
                                .addComponent(jComboBoxTipoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jComboBoxSituacaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jTextFieldAnoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jTextFieldnPaginasEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24))))
            .addGroup(jPanelEditar1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabelResumoEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelAbstractTextEditar)
                .addGap(139, 139, 139))
        );
        jPanelEditar1Layout.setVerticalGroup(
            jPanelEditar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTituloEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAutorEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldAutorEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelOrientadorEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldOrientadorEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEditar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoEditar)
                    .addComponent(jLabelSituacaoEditar)
                    .addComponent(jLabelAnoEditar)
                    .addComponent(jLabelnPaginasEditar))
                .addGap(7, 7, 7)
                .addGroup(jPanelEditar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTipoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSituacaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAnoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldnPaginasEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelInstituicaoEditar)
                .addGap(10, 10, 10)
                .addComponent(jTextFieldInstituicaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCursoEditar)
                .addGap(5, 5, 5)
                .addComponent(jTextFieldCrusoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelPalavrasChavesEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEditar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPalavraChaveEditar0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPalavraChaveEditar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPalavraChaveEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPalavraChaveEditar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanelEditar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelResumoEditar)
                    .addComponent(jLabelAbstractTextEditar))
                .addGap(18, 18, 18)
                .addGroup(jPanelEditar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane6.setViewportView(jPanelEditar1);

        javax.swing.GroupLayout jPanelEditarLayout = new javax.swing.GroupLayout(jPanelEditar);
        jPanelEditar.setLayout(jPanelEditarLayout);
        jPanelEditarLayout.setHorizontalGroup(
            jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jCancelarButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSalvarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jPanelEditarLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelEditarLayout.setVerticalGroup(
            jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditarLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCancelarButton1)
                    .addComponent(jSalvarButton1))
                .addGap(23, 23, 23))
        );

        jTabbedPaneMonografia.addTab("Editar", jPanelEditar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneMonografia, javax.swing.GroupLayout.PREFERRED_SIZE, 563, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneMonografia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPaneMonografiaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPaneMonografiaStateChanged
        //if (jMonografiaTabbedPanel.getSelectedIndex() == 0) {
        //   MonografiaCrud.listar(jMonografiaList);
        // }
    }//GEN-LAST:event_jTabbedPaneMonografiaStateChanged

    private void jTextFieldCrusoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCrusoEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCrusoEditarActionPerformed

    private void jSalvarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalvarButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSalvarButton1ActionPerformed

    private void jTextFieldCrusoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCrusoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCrusoActionPerformed

    private void jButtonConsultaAvancadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaAvancadaActionPerformed
        jTabbedPaneMonografia.setSelectedIndex(1);
        jTabbedPaneMonografia.setEnabledAt(1, true);
        jTabbedPaneMonografia.setEnabledAt(0, false);
    }//GEN-LAST:event_jButtonConsultaAvancadaActionPerformed

    private void jButtonConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaActionPerformed

        //MonografiaCrud.setMonografiaList(CrudMonografiaObjects.readObject("blablabla"));
        displayList = MonografiaCrud.consultar(jComboBoxConsulta.getSelectedItem().toString(), jTextFieldConsulta.getText());
        listar();
    }//GEN-LAST:event_jButtonConsultaActionPerformed

    private void jlButtonVoltarMenuIniciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlButtonVoltarMenuIniciaActionPerformed
        new Inicial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jlButtonVoltarMenuIniciaActionPerformed

    private void jButtonExcluirMonografiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirMonografiaActionPerformed

        MonografiaCrud.excluir(jListMonografia.getSelectedValue());
        displayList = MonografiaCrud.consultar("", "");

        listar();
    }//GEN-LAST:event_jButtonExcluirMonografiaActionPerformed

    private void jButtonAdicionarMonografiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarMonografiaActionPerformed
        jTabbedPaneMonografia.setSelectedIndex(1);
        jTabbedPaneMonografia.setEnabledAt(1, true);
        jTabbedPaneMonografia.setEnabledAt(0, false);
    }//GEN-LAST:event_jButtonAdicionarMonografiaActionPerformed

    private void jListMonografiaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListMonografiaValueChanged
        if (jListMonografia.isSelectionEmpty() == false) {
            jButtonEditarMonografia.setEnabled(true);
            jButtonExcluirMonografia.setEnabled(true);
        } else {
            jButtonEditarMonografia.setEnabled(false);
            jButtonExcluirMonografia.setEnabled(false);
        }
    }//GEN-LAST:event_jListMonografiaValueChanged

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        String titulo, autor, orientador, tipo, situacao, instituicao, curso, abstractText, resumo;
        String[] palavrasChave = new String[4];
        int ano = 0, nPaginas = 0;

        titulo = jTextFieldTitulo.getText();
        autor = jTextFieldAutor.getText();
        orientador = jTextFieldOrientador.getText();
        tipo = jComboBoxTipo.getSelectedItem().toString();
        situacao = jComboBoxSituacao.getSelectedItem().toString();

        if (jTextFieldAno.getText().isEmpty() == false) {
            ano = Integer.valueOf(jTextFieldAno.getText());
        }

        if (jTextFieldnPaginas.getText().isEmpty() == false) {
            nPaginas = Integer.valueOf(jTextFieldnPaginas.getText());
        }

        instituicao = jTextFieldInstituicao.getText();
        curso = jTextFieldCruso.getText();

        palavrasChave[0] = jTextFieldPalavraChave0.getText();
        palavrasChave[1] = jTextFieldPalavraChave1.getText();
        palavrasChave[2] = jTextFieldPalavraChave2.getText();
        palavrasChave[3] = jTextFieldPalavraChave3.getText();

        resumo = jTextPaneResumo.getText();
        abstractText = jTextPaneAbstractText.getText();

        MonografiaCrud.adicionar(titulo, autor, orientador, tipo, situacao, ano, nPaginas, instituicao, curso, palavrasChave, resumo, abstractText);

        jTabbedPaneMonografia.setEnabledAt(0, true);
        jTabbedPaneMonografia.setEnabledAt(1, false);
        jTabbedPaneMonografia.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonEditarMonografiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarMonografiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditarMonografiaActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMonografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMonografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMonografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMonografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMonografia().setVisible(true);
            }
        });
    }

    private void listar() {

        DefaultListModel listModel = new DefaultListModel();

        for (String element : displayList) {
            listModel.addElement(element);
        }

        jListMonografia.setModel(listModel);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarMonografia;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConsulta;
    private javax.swing.JButton jButtonConsultaAvancada;
    private javax.swing.JButton jButtonEditarMonografia;
    private javax.swing.JButton jButtonExcluirMonografia;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jCancelarButton1;
    private javax.swing.JComboBox<String> jComboBoxConsulta;
    private javax.swing.JComboBox<String> jComboBoxSituacao;
    private javax.swing.JComboBox<String> jComboBoxSituacaoEditar;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JComboBox<String> jComboBoxTipoEditar;
    private javax.swing.JLabel jLabelAbstractText;
    private javax.swing.JLabel jLabelAbstractTextEditar;
    private javax.swing.JLabel jLabelAno;
    private javax.swing.JLabel jLabelAnoEditar;
    private javax.swing.JLabel jLabelAutor;
    private javax.swing.JLabel jLabelAutorEditar;
    private javax.swing.JLabel jLabelConsulta;
    private javax.swing.JLabel jLabelCurso;
    private javax.swing.JLabel jLabelCursoEditar;
    private javax.swing.JLabel jLabelInstituicao;
    private javax.swing.JLabel jLabelInstituicaoEditar;
    private javax.swing.JLabel jLabelOrientador;
    private javax.swing.JLabel jLabelOrientadorEditar;
    private javax.swing.JLabel jLabelPalavrasChaves;
    private javax.swing.JLabel jLabelPalavrasChavesEditar;
    private javax.swing.JLabel jLabelResumo;
    private javax.swing.JLabel jLabelResumoEditar;
    private javax.swing.JLabel jLabelSituacao;
    private javax.swing.JLabel jLabelSituacaoEditar;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelTipoEditar;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTituloEditar;
    private javax.swing.JLabel jLabelnPaginas;
    private javax.swing.JLabel jLabelnPaginasEditar;
    private javax.swing.JList<String> jListMonografia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAdicionar;
    private javax.swing.JPanel jPanelEditar;
    private javax.swing.JPanel jPanelEditar1;
    private javax.swing.JPanel jPanelListar;
    private javax.swing.JButton jSalvarButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPaneMonografias;
    private javax.swing.JTabbedPane jTabbedPaneMonografia;
    private javax.swing.JTextField jTextFieldAno;
    private javax.swing.JTextField jTextFieldAnoEditar;
    private javax.swing.JTextField jTextFieldAutor;
    private javax.swing.JTextField jTextFieldAutorEditar;
    private javax.swing.JTextField jTextFieldConsulta;
    private javax.swing.JTextField jTextFieldCruso;
    private javax.swing.JTextField jTextFieldCrusoEditar;
    private javax.swing.JTextField jTextFieldInstituicao;
    private javax.swing.JTextField jTextFieldInstituicaoEditar;
    private javax.swing.JTextField jTextFieldOrientador;
    private javax.swing.JTextField jTextFieldOrientadorEditar;
    private javax.swing.JTextField jTextFieldPalavraChave0;
    private javax.swing.JTextField jTextFieldPalavraChave1;
    private javax.swing.JTextField jTextFieldPalavraChave2;
    private javax.swing.JTextField jTextFieldPalavraChave3;
    private javax.swing.JTextField jTextFieldPalavraChaveEditar0;
    private javax.swing.JTextField jTextFieldPalavraChaveEditar1;
    private javax.swing.JTextField jTextFieldPalavraChaveEditar2;
    private javax.swing.JTextField jTextFieldPalavraChaveEditar3;
    private javax.swing.JTextField jTextFieldTitulo;
    private javax.swing.JTextField jTextFieldTituloEditar;
    private javax.swing.JTextField jTextFieldnPaginas;
    private javax.swing.JTextField jTextFieldnPaginasEditar;
    private javax.swing.JTextPane jTextPaneAbstractText;
    private javax.swing.JTextPane jTextPaneAbstractTextEditar;
    private javax.swing.JTextPane jTextPaneResumo;
    private javax.swing.JTextPane jTextPaneResumoEditar;
    private javax.swing.JButton jlButtonVoltarMenuInicia;
    // End of variables declaration//GEN-END:variables
}
