/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import categorias.ShortCourse;
import cruds.ShortCourseCrud;
import java.util.List;

/**
 *
 * @author YuryAlencar
 */
public class MoreDetailsShortCourse extends javax.swing.JFrame {

    List<ShortCourse> shortCourseList = ShortCourseCrud.getShortCourseList();
    /**
     * Creates new form MoreDetailsShortCourse
     */
    public MoreDetailsShortCourse(String titleDetails) {
        initComponents();
        this.setTitle("RP II - Detalhes");
        this.setLocationRelativeTo(null);
        
        int indexSituation = 0, indexNumberAuthors = 0;
        
        for(ShortCourse course : shortCourseList){
            if(course.getTitle().equals(titleDetails)){
                for(int i=0; i<jComboBoxMoreDetailsSituation.getItemCount(); i++){
                    if(course.getSituation().equals(jComboBoxMoreDetailsSituation.getItemAt(i))){
                        indexSituation = i;
                    }
                }
                jTextMoreDetailsTitle.setText(course.getTitle());
                jComboBoxMoreDetailsSituation.setSelectedIndex(indexSituation);
                jTextPaneMoreDetailsResumoText.setText(course.getResumoText());
                jTextPaneMoreDetailsAbstractText.setText(course.getAbstractText());
                jFormattedTextMoreDetailsDuration.setText(course.getDuration());
                jTextPaneMoreDetailsMethodology.setText(course.getMethodology());
                jTextMoreDetailsResources.setText(course.getResources());
                jTextMoreDetailsAuthor.setText(course.getAuthor()[0]);
                jTextMoreDetailsAuthor1.setText(course.getAuthor()[1]);
                jTextMoreDetailsAuthor2.setText(course.getAuthor()[2]);
                if(!(jTextMoreDetailsAuthor1.getText().trim().equals("")))
                    indexNumberAuthors = 1;
                if(!(jTextMoreDetailsAuthor2.getText().trim().equals("")))
                    indexNumberAuthors = 2;
                jComboBoxMoreDetailsNumberAuthors.setSelectedIndex(indexNumberAuthors);
                
            }
        }
        
        jTextMoreDetailsTitle.setEnabled(false);
        jComboBoxMoreDetailsSituation.setEnabled(false);
        jTextPaneMoreDetailsResumoText.setEnabled(false);
        jTextPaneMoreDetailsAbstractText.setEnabled(false);
        jFormattedTextMoreDetailsDuration.setEnabled(false);
        jComboBoxMoreDetailsNumberAuthors.setEnabled(false);
        jTextPaneMoreDetailsMethodology.setEnabled(false);
        jTextMoreDetailsResources.setEnabled(false);
        jTextMoreDetailsAuthor.setEnabled(false);
        jTextMoreDetailsAuthor1.setEnabled(false);
        jTextMoreDetailsAuthor2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMoreDetails = new javax.swing.JPanel();
        jLabelMoreDetailsTitle = new javax.swing.JLabel();
        jTextMoreDetailsTitle = new javax.swing.JTextField();
        jComboBoxMoreDetailsSituation = new javax.swing.JComboBox<>();
        jLabelMoreDetailsSituation = new javax.swing.JLabel();
        jLabelMoreDetailsResumoText = new javax.swing.JLabel();
        jScrollPaneMoreDetailsResumoText = new javax.swing.JScrollPane();
        jTextPaneMoreDetailsAbstractText = new javax.swing.JTextPane();
        jScrollPaneMoreDetailsAbstractText = new javax.swing.JScrollPane();
        jTextPaneMoreDetailsResumoText = new javax.swing.JTextPane();
        jLabelMoreDetailsAbstractText = new javax.swing.JLabel();
        jLabelMoreDetailsDuration = new javax.swing.JLabel();
        jFormattedTextMoreDetailsDuration = new javax.swing.JFormattedTextField();
        jLabelMoreDetailsResources = new javax.swing.JLabel();
        jTextMoreDetailsResources = new javax.swing.JTextField();
        jLabelMoreDetailsMethodology = new javax.swing.JLabel();
        jScrollPaneMoreDetailsMethodology = new javax.swing.JScrollPane();
        jTextPaneMoreDetailsMethodology = new javax.swing.JTextPane();
        jLabelMoreDetailsAuthor = new javax.swing.JLabel();
        jTextMoreDetailsAuthor = new javax.swing.JTextField();
        jComboBoxMoreDetailsNumberAuthors = new javax.swing.JComboBox<>();
        jTextMoreDetailsAuthor1 = new javax.swing.JTextField();
        jTextMoreDetailsAuthor2 = new javax.swing.JTextField();
        jButtonMoreDetailsBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelMoreDetailsTitle.setText("Título: ");

        jComboBoxMoreDetailsSituation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sob avaliação", "Aprovado", "Reprovado" }));

        jLabelMoreDetailsSituation.setText("Situação:");

        jLabelMoreDetailsResumoText.setText("Resumo:");

        jScrollPaneMoreDetailsResumoText.setViewportView(jTextPaneMoreDetailsAbstractText);

        jScrollPaneMoreDetailsAbstractText.setViewportView(jTextPaneMoreDetailsResumoText);

        jLabelMoreDetailsAbstractText.setText("Abstract:");

        jLabelMoreDetailsDuration.setText("Duração:");

        try {
            jFormattedTextMoreDetailsDuration.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelMoreDetailsResources.setText("Recursos:");

        jLabelMoreDetailsMethodology.setText("Metodologia:");

        jScrollPaneMoreDetailsMethodology.setViewportView(jTextPaneMoreDetailsMethodology);

        jLabelMoreDetailsAuthor.setText("Autor:");

        jComboBoxMoreDetailsNumberAuthors.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        jButtonMoreDetailsBack.setText("Voltar");
        jButtonMoreDetailsBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoreDetailsBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMoreDetailsLayout = new javax.swing.GroupLayout(jPanelMoreDetails);
        jPanelMoreDetails.setLayout(jPanelMoreDetailsLayout);
        jPanelMoreDetailsLayout.setHorizontalGroup(
            jPanelMoreDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMoreDetailsLayout.createSequentialGroup()
                .addGroup(jPanelMoreDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMoreDetailsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelMoreDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelMoreDetailsLayout.createSequentialGroup()
                                .addGroup(jPanelMoreDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelMoreDetailsLayout.createSequentialGroup()
                                        .addComponent(jLabelMoreDetailsTitle)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextMoreDetailsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelMoreDetailsLayout.createSequentialGroup()
                                        .addComponent(jLabelMoreDetailsSituation)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBoxMoreDetailsSituation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanelMoreDetailsLayout.createSequentialGroup()
                                        .addComponent(jLabelMoreDetailsResumoText)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPaneMoreDetailsAbstractText, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelMoreDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelMoreDetailsLayout.createSequentialGroup()
                                        .addComponent(jLabelMoreDetailsDuration)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextMoreDetailsDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelMoreDetailsLayout.createSequentialGroup()
                                        .addComponent(jLabelMoreDetailsResources)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextMoreDetailsResources, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelMoreDetailsLayout.createSequentialGroup()
                                        .addComponent(jLabelMoreDetailsMethodology)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPaneMoreDetailsMethodology, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanelMoreDetailsLayout.createSequentialGroup()
                                .addComponent(jLabelMoreDetailsAbstractText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPaneMoreDetailsResumoText, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelMoreDetailsAuthor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelMoreDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelMoreDetailsLayout.createSequentialGroup()
                                        .addComponent(jTextMoreDetailsAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBoxMoreDetailsNumberAuthors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextMoreDetailsAuthor2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextMoreDetailsAuthor1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanelMoreDetailsLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jButtonMoreDetailsBack, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        jPanelMoreDetailsLayout.setVerticalGroup(
            jPanelMoreDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMoreDetailsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelMoreDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMoreDetailsTitle)
                    .addComponent(jTextMoreDetailsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMoreDetailsDuration)
                    .addComponent(jFormattedTextMoreDetailsDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMoreDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMoreDetailsSituation)
                    .addComponent(jComboBoxMoreDetailsSituation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMoreDetailsResources)
                    .addComponent(jTextMoreDetailsResources, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMoreDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelMoreDetailsResumoText)
                    .addComponent(jLabelMoreDetailsMethodology)
                    .addComponent(jScrollPaneMoreDetailsMethodology, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPaneMoreDetailsAbstractText, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanelMoreDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelMoreDetailsAbstractText)
                    .addGroup(jPanelMoreDetailsLayout.createSequentialGroup()
                        .addGroup(jPanelMoreDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMoreDetailsAuthor)
                            .addComponent(jTextMoreDetailsAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxMoreDetailsNumberAuthors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jTextMoreDetailsAuthor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextMoreDetailsAuthor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneMoreDetailsResumoText, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jButtonMoreDetailsBack)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMoreDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMoreDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMoreDetailsBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoreDetailsBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonMoreDetailsBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoreDetailsShortCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoreDetailsShortCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoreDetailsShortCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoreDetailsShortCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MoreDetailsShortCourse(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMoreDetailsBack;
    private javax.swing.JComboBox<String> jComboBoxMoreDetailsNumberAuthors;
    private javax.swing.JComboBox<String> jComboBoxMoreDetailsSituation;
    private javax.swing.JFormattedTextField jFormattedTextMoreDetailsDuration;
    private javax.swing.JLabel jLabelMoreDetailsAbstractText;
    private javax.swing.JLabel jLabelMoreDetailsAuthor;
    private javax.swing.JLabel jLabelMoreDetailsDuration;
    private javax.swing.JLabel jLabelMoreDetailsMethodology;
    private javax.swing.JLabel jLabelMoreDetailsResources;
    private javax.swing.JLabel jLabelMoreDetailsResumoText;
    private javax.swing.JLabel jLabelMoreDetailsSituation;
    private javax.swing.JLabel jLabelMoreDetailsTitle;
    private javax.swing.JPanel jPanelMoreDetails;
    private javax.swing.JScrollPane jScrollPaneMoreDetailsAbstractText;
    private javax.swing.JScrollPane jScrollPaneMoreDetailsMethodology;
    private javax.swing.JScrollPane jScrollPaneMoreDetailsResumoText;
    private javax.swing.JTextField jTextMoreDetailsAuthor;
    private javax.swing.JTextField jTextMoreDetailsAuthor1;
    private javax.swing.JTextField jTextMoreDetailsAuthor2;
    private javax.swing.JTextField jTextMoreDetailsResources;
    private javax.swing.JTextField jTextMoreDetailsTitle;
    private javax.swing.JTextPane jTextPaneMoreDetailsAbstractText;
    private javax.swing.JTextPane jTextPaneMoreDetailsMethodology;
    private javax.swing.JTextPane jTextPaneMoreDetailsResumoText;
    // End of variables declaration//GEN-END:variables
}
