/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;
import categorias.ShortCourse;
import cruds.ShortCourseCrud;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
/**
 *
 * @author YuryAlencar
 */
public class PanelShortCourse extends javax.swing.JFrame {
    
    String nameToEdit;
    List<categorias.ShortCourse> courseList = ShortCourseCrud.getShortCourseList();
    /**
     * Creates new form panelShortCourse
     */
    public PanelShortCourse() {

        initComponents();
        this.setTitle("RP II - Minicursos");
        this.setLocationRelativeTo(null);

        jTextAuthor1Edit.setEnabled(false);
        jTextAuthor2Edit.setEnabled(false);
        
        jButtonEdit.setEnabled(false);
        jButtonDelete.setEnabled(false);
        jButtonMoreDetails.setEnabled(false);
        
        jTextAuthor1.setEnabled(false);
        jTextAuthor2.setEnabled(false);

        jTabShortCourse.setEnabledAt(2, false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabShortCourse = new javax.swing.JTabbedPane();
        jPanelList = new javax.swing.JPanel();
        jButtonMoreDetails = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonBackListInit = new javax.swing.JButton();
        jScrollPaneNamesShortCourses = new javax.swing.JScrollPane();
        jListNamesShortCourses = new javax.swing.JList<>();
        jLabelConsult = new javax.swing.JLabel();
        jTextConsult = new javax.swing.JTextField();
        jComboBoxConsult = new javax.swing.JComboBox<>();
        jButtonConsult = new javax.swing.JButton();
        jPanelInsert = new javax.swing.JPanel();
        jButtonSaveInsert = new javax.swing.JButton();
        jButtonBackInsertInit = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jTextTitle = new javax.swing.JTextField();
        jLabelSituation = new javax.swing.JLabel();
        jComboBoxSituation = new javax.swing.JComboBox<>();
        jLabelResumoText = new javax.swing.JLabel();
        jScrollPaneResumoText = new javax.swing.JScrollPane();
        jTextPaneResumoText = new javax.swing.JTextPane();
        jLabelAbstractText = new javax.swing.JLabel();
        jScrollPaneAbstractText = new javax.swing.JScrollPane();
        jTextPaneAbstractText = new javax.swing.JTextPane();
        jLabelDuration = new javax.swing.JLabel();
        jFormattedDuration = new javax.swing.JFormattedTextField();
        jLabelResources = new javax.swing.JLabel();
        jTextResources = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPaneMethodology = new javax.swing.JScrollPane();
        jTextPaneMethodology = new javax.swing.JTextPane();
        jLabelAuthor = new javax.swing.JLabel();
        jTextAuthor = new javax.swing.JTextField();
        jTextAuthor1 = new javax.swing.JTextField();
        jTextAuthor2 = new javax.swing.JTextField();
        jComboBoxAuthorInsert = new javax.swing.JComboBox<>();
        jPanelEdit = new javax.swing.JPanel();
        jButtonSaveEdit = new javax.swing.JButton();
        jButtonBackList = new javax.swing.JButton();
        jLabelTitleEdit = new javax.swing.JLabel();
        jTextTitleEdit = new javax.swing.JTextField();
        jLabelSituationEdit = new javax.swing.JLabel();
        jComboBoxSituationEdit = new javax.swing.JComboBox<>();
        jLabelResumoTextEdit = new javax.swing.JLabel();
        jScrollPaneResumoTextEdit = new javax.swing.JScrollPane();
        jTextPaneResumoTextEdit = new javax.swing.JTextPane();
        jLabelAbstractTextEdit = new javax.swing.JLabel();
        jScrollPaneAbstractTextEdit = new javax.swing.JScrollPane();
        jTextPaneAbstractTextEdit = new javax.swing.JTextPane();
        jLabelDurationEdit = new javax.swing.JLabel();
        jFormattedDurationEdit = new javax.swing.JFormattedTextField();
        jLabelResourcesEdit = new javax.swing.JLabel();
        jTextResourcesEdit = new javax.swing.JTextField();
        jLabelMethodologyEdit = new javax.swing.JLabel();
        jScrollPaneMethodologyEdit = new javax.swing.JScrollPane();
        jTextPaneMethodologyEdit = new javax.swing.JTextPane();
        jLabelAuthorEdit = new javax.swing.JLabel();
        jTextAuthorEdit = new javax.swing.JTextField();
        jTextAuthor1Edit = new javax.swing.JTextField();
        jTextAuthor2Edit = new javax.swing.JTextField();
        jComboBoxAuthorEdit = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonMoreDetails.setText("Mais Detalhes");

        jButtonEdit.setText("Editar");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Excluir");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonBackListInit.setText("Voltar");
        jButtonBackListInit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackListInitActionPerformed(evt);
            }
        });

        jListNamesShortCourses.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListNamesShortCoursesValueChanged(evt);
            }
        });
        jScrollPaneNamesShortCourses.setViewportView(jListNamesShortCourses);

        jLabelConsult.setText("Consultar por:");

        jComboBoxConsult.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Listar todos", "Titulo", "Autor" }));

        jButtonConsult.setText("Consultar");
        jButtonConsult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelListLayout = new javax.swing.GroupLayout(jPanelList);
        jPanelList.setLayout(jPanelListLayout);
        jPanelListLayout.setHorizontalGroup(
            jPanelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextConsult, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelListLayout.createSequentialGroup()
                        .addComponent(jLabelConsult)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxConsult, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelListLayout.createSequentialGroup()
                        .addGroup(jPanelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonMoreDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonBackListInit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelListLayout.createSequentialGroup()
                                .addComponent(jButtonConsult, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 110, Short.MAX_VALUE))
                            .addComponent(jScrollPaneNamesShortCourses))))
                .addContainerGap())
        );
        jPanelListLayout.setVerticalGroup(
            jPanelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConsult)
                    .addComponent(jComboBoxConsult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextConsult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonConsult)
                .addGap(30, 30, 30)
                .addGroup(jPanelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelListLayout.createSequentialGroup()
                        .addComponent(jButtonMoreDetails)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEdit)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addComponent(jButtonBackListInit))
                    .addComponent(jScrollPaneNamesShortCourses))
                .addContainerGap())
        );

        jTabShortCourse.addTab("Lista", jPanelList);

        jButtonSaveInsert.setText("Salvar");
        jButtonSaveInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveInsertActionPerformed(evt);
            }
        });

        jButtonBackInsertInit.setText("Voltar");
        jButtonBackInsertInit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackInsertInitActionPerformed(evt);
            }
        });

        jLabelTitle.setText("Título: ");

        jLabelSituation.setText("Situação:");

        jComboBoxSituation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sob avaliação", "Aprovado", "Reprovado" }));

        jLabelResumoText.setText("Resumo: ");

        jScrollPaneResumoText.setViewportView(jTextPaneResumoText);

        jLabelAbstractText.setText("Abstract:");

        jScrollPaneAbstractText.setViewportView(jTextPaneAbstractText);

        jLabelDuration.setText("Duração:");

        try {
            jFormattedDuration.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelResources.setText("Recursos:");

        jLabel1.setText("Metodologia:");

        jScrollPaneMethodology.setViewportView(jTextPaneMethodology);

        jLabelAuthor.setText("Autor:");

        jComboBoxAuthorInsert.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jComboBoxAuthorInsert.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxAuthorInsertItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanelInsertLayout = new javax.swing.GroupLayout(jPanelInsert);
        jPanelInsert.setLayout(jPanelInsertLayout);
        jPanelInsertLayout.setHorizontalGroup(
            jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInsertLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInsertLayout.createSequentialGroup()
                        .addGroup(jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelInsertLayout.createSequentialGroup()
                                .addComponent(jLabelAbstractText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPaneAbstractText))
                            .addGroup(jPanelInsertLayout.createSequentialGroup()
                                .addComponent(jLabelTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelInsertLayout.createSequentialGroup()
                                .addGroup(jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSituation)
                                    .addComponent(jLabelResumoText))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPaneResumoText)
                                    .addComponent(jComboBoxSituation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInsertLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPaneMethodology))
                            .addGroup(jPanelInsertLayout.createSequentialGroup()
                                .addGroup(jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDuration)
                                    .addComponent(jLabelResources))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextResources)
                                    .addGroup(jPanelInsertLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jFormattedDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInsertLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextAuthor2)
                                    .addComponent(jTextAuthor1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInsertLayout.createSequentialGroup()
                                .addComponent(jLabelAuthor)
                                .addGap(0, 0, 0)
                                .addComponent(jTextAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxAuthorInsert, 0, 61, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInsertLayout.createSequentialGroup()
                        .addComponent(jButtonBackInsertInit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSaveInsert)))
                .addContainerGap())
        );
        jPanelInsertLayout.setVerticalGroup(
            jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInsertLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitle)
                    .addComponent(jTextTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDuration)
                    .addComponent(jFormattedDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelSituation)
                        .addComponent(jLabelResources)
                        .addComponent(jTextResources, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBoxSituation))
                .addGap(12, 12, 12)
                .addGroup(jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneMethodology)
                    .addComponent(jLabel1)
                    .addComponent(jLabelResumoText)
                    .addComponent(jScrollPaneResumoText, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelAbstractText)
                    .addGroup(jPanelInsertLayout.createSequentialGroup()
                        .addGroup(jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAuthor)
                            .addComponent(jTextAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxAuthorInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextAuthor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextAuthor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneAbstractText))
                .addGap(53, 53, 53)
                .addGroup(jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSaveInsert)
                    .addComponent(jButtonBackInsertInit))
                .addContainerGap())
        );

        jTabShortCourse.addTab("Adicionar", jPanelInsert);

        jButtonSaveEdit.setText("Salvar");
        jButtonSaveEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveEditActionPerformed(evt);
            }
        });

        jButtonBackList.setText("Voltar");
        jButtonBackList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackListActionPerformed(evt);
            }
        });

        jLabelTitleEdit.setText("Titulo:");

        jLabelSituationEdit.setText("Situação:");

        jComboBoxSituationEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sob avaliação", "Aprovado", "Reprovado" }));

        jLabelResumoTextEdit.setText("Resumo:");

        jTextPaneResumoTextEdit.setMaximumSize(new java.awt.Dimension(6, 10));
        jScrollPaneResumoTextEdit.setViewportView(jTextPaneResumoTextEdit);

        jLabelAbstractTextEdit.setText("Abstract:");

        jTextPaneAbstractTextEdit.setMaximumSize(new java.awt.Dimension(6, 20));
        jScrollPaneAbstractTextEdit.setViewportView(jTextPaneAbstractTextEdit);

        jLabelDurationEdit.setText("Duração:");

        try {
            jFormattedDurationEdit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelResourcesEdit.setText("Recursos:");

        jLabelMethodologyEdit.setText("Metodologia:");

        jTextPaneMethodologyEdit.setMaximumSize(new java.awt.Dimension(6, 20));
        jScrollPaneMethodologyEdit.setViewportView(jTextPaneMethodologyEdit);

        jLabelAuthorEdit.setText("Autor: ");

        jComboBoxAuthorEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jComboBoxAuthorEdit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxAuthorEditItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanelEditLayout = new javax.swing.GroupLayout(jPanelEdit);
        jPanelEdit.setLayout(jPanelEditLayout);
        jPanelEditLayout.setHorizontalGroup(
            jPanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEditLayout.createSequentialGroup()
                        .addGroup(jPanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelEditLayout.createSequentialGroup()
                                .addComponent(jLabelTitleEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextTitleEdit))
                            .addGroup(jPanelEditLayout.createSequentialGroup()
                                .addComponent(jLabelSituationEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxSituationEdit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelEditLayout.createSequentialGroup()
                                .addComponent(jLabelResumoTextEdit)
                                .addGap(5, 5, 5)
                                .addComponent(jScrollPaneResumoTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelEditLayout.createSequentialGroup()
                                .addComponent(jLabelAbstractTextEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPaneAbstractTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEditLayout.createSequentialGroup()
                                .addComponent(jLabelMethodologyEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPaneMethodologyEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelEditLayout.createSequentialGroup()
                                .addComponent(jLabelDurationEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedDurationEdit))
                            .addGroup(jPanelEditLayout.createSequentialGroup()
                                .addComponent(jLabelAuthorEdit)
                                .addGap(0, 0, 0)
                                .addComponent(jTextAuthorEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxAuthorEdit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(4, 4, 4))
                            .addGroup(jPanelEditLayout.createSequentialGroup()
                                .addComponent(jLabelResourcesEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextResourcesEdit))
                            .addGroup(jPanelEditLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextAuthor1Edit)
                                    .addComponent(jTextAuthor2Edit)))))
                    .addGroup(jPanelEditLayout.createSequentialGroup()
                        .addComponent(jButtonBackList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSaveEdit)))
                .addContainerGap())
        );
        jPanelEditLayout.setVerticalGroup(
            jPanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEditLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitleEdit)
                    .addComponent(jTextTitleEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDurationEdit)
                    .addComponent(jFormattedDurationEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSituationEdit)
                    .addComponent(jComboBoxSituationEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelResourcesEdit)
                    .addComponent(jTextResourcesEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelResumoTextEdit)
                    .addComponent(jLabelMethodologyEdit)
                    .addComponent(jScrollPaneMethodologyEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPaneResumoTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAbstractTextEdit)
                    .addComponent(jScrollPaneAbstractTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEditLayout.createSequentialGroup()
                        .addGroup(jPanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEditLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jTextAuthor1Edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextAuthorEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelAuthorEdit)
                                .addComponent(jComboBoxAuthorEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextAuthor2Edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69)
                .addGroup(jPanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBackList)
                    .addComponent(jButtonSaveEdit))
                .addContainerGap())
        );

        jTabShortCourse.addTab("Editar", jPanelEdit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabShortCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabShortCourse)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackInsertInitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackInsertInitActionPerformed
        // TODO add your handling code here:
        Inicial back = new Inicial();
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBackInsertInitActionPerformed

    private void jButtonBackListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackListActionPerformed
        // TODO add your handling code here:
        jTabShortCourse.setSelectedIndex(0);
        jTabShortCourse.setEnabledAt(0, true);
        jTabShortCourse.setEnabledAt(1, true);
        jTabShortCourse.setEnabledAt(2, false);
    }//GEN-LAST:event_jButtonBackListActionPerformed

    private void jButtonBackListInitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackListInitActionPerformed
        // TODO add your handling code here:
        Inicial back = new Inicial();
        back.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_jButtonBackListInitActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
        jTabShortCourse.setSelectedIndex(2);
        jTabShortCourse.setEnabledAt(0, false);
        jTabShortCourse.setEnabledAt(1, false);
        jTabShortCourse.setEnabledAt(2, true);
        
        int indexEditSituation = 0, indexAuthorEdit = 0;
        nameToEdit = jListNamesShortCourses.getSelectedValue();
        
        for(categorias.ShortCourse course : courseList){
            if(nameToEdit.equals(course.getTitle())){
                for(int i=0; i<jComboBoxAuthorEdit.getItemCount(); i++){
                    if(course.getSituation().equals(jComboBoxSituationEdit.getItemAt(i))){
                        indexEditSituation = i;
                    }
                }
                jTextTitleEdit.setText(course.getTitle());
                jComboBoxSituationEdit.setSelectedIndex(indexEditSituation);
                jTextPaneResumoTextEdit.setText(course.getResumoText());
                jTextPaneAbstractTextEdit.setText(course.getAbstractText());
                jFormattedDurationEdit.setText(course.getDuration());
                jTextResourcesEdit.setText(course.getResources());
                jTextPaneMethodologyEdit.setText(course.getMethodology());
                jTextAuthorEdit.setText(course.getAuthor()[0]);
                jTextAuthor1Edit.setText(course.getAuthor()[1]);
                jTextAuthor2Edit.setText(course.getAuthor()[2]);
                if(!(jTextAuthor1Edit.getText().trim().equals("")))
                    indexAuthorEdit = 1;
                if(!(jTextAuthor2Edit.getText().trim().equals("")))
                    indexAuthorEdit = 2;
                jComboBoxAuthorEdit.setSelectedIndex(indexAuthorEdit);
            }
        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonSaveInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveInsertActionPerformed
        // TODO add your handling code here:
        cruds.ShortCourseCrud insert = new cruds.ShortCourseCrud();
        insert.insertCourse(jTextTitle.getText(), jComboBoxSituation.getSelectedItem().toString(), jTextPaneResumoText.getText(), jTextPaneAbstractText.getText(), jFormattedDuration.getText(), jTextResources.getText(), jTextPaneMethodology.getText(), jTextAuthor.getText(), jTextAuthor1.getText(), jTextAuthor2.getText());

        jTextTitle.setText("");
        jComboBoxSituation.setSelectedIndex(0);
        jTextPaneResumoText.setText("");
        jTextPaneAbstractText.setText("");
        jFormattedDuration.setText("");
        jTextResources.setText(""); 
        jTextPaneMethodology.setText("");
        jTextAuthor.setText("");
        jTextAuthor1.setText("");
        jTextAuthor2.setText("");
    }//GEN-LAST:event_jButtonSaveInsertActionPerformed

    private void jButtonSaveEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveEditActionPerformed
        // TODO add your handling code here:
        cruds.ShortCourseCrud edit = new cruds.ShortCourseCrud();
        edit.editCourse(nameToEdit, jTextTitleEdit.getText(), jComboBoxSituationEdit.getSelectedItem().toString(), jTextPaneResumoTextEdit.getText(), jTextPaneAbstractTextEdit.getText(), jFormattedDurationEdit.getText(), jTextResourcesEdit.getText(), jTextPaneMethodologyEdit.getText(), jTextAuthorEdit.getText(), jTextAuthor1Edit.getText(), jTextAuthor2Edit.getText());

        ShortCourseCrud.consult(jComboBoxConsult.getSelectedItem().toString(), jTextConsult.getText());
        ShortCourseCrud.list(jListNamesShortCourses);

        jTabShortCourse.setSelectedIndex(0);
        jTabShortCourse.setEnabledAt(0, true);
        jTabShortCourse.setEnabledAt(1, true);
        jTabShortCourse.setEnabledAt(2, false);
    }//GEN-LAST:event_jButtonSaveEditActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        ShortCourseCrud.deleteCourse(jListNamesShortCourses.getSelectedValue());
        ShortCourseCrud.consult("","");
        ShortCourseCrud.list(jListNamesShortCourses);
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jListNamesShortCoursesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListNamesShortCoursesValueChanged
        // TODO add your handling code here:
        if(jListNamesShortCourses.isSelectionEmpty()){
            jButtonEdit.setEnabled(false);
            jButtonDelete.setEnabled(false);
            jButtonMoreDetails.setEnabled(false);
        } else {
            jButtonEdit.setEnabled(true);
            jButtonDelete.setEnabled(true);
            jButtonMoreDetails.setEnabled(true);
        }
    }//GEN-LAST:event_jListNamesShortCoursesValueChanged

    private void jComboBoxAuthorInsertItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxAuthorInsertItemStateChanged
        // TODO add your handling code here:
        switch(jComboBoxAuthorInsert.getSelectedItem().toString()){
            case "1":
                jTextAuthor.setEnabled(true);
                jTextAuthor1.setEnabled(false);
                jTextAuthor2.setEnabled(false);
                break;
            case "2":
                jTextAuthor.setEnabled(true);
                jTextAuthor1.setEnabled(true);
                jTextAuthor2.setEnabled(false);
                break;
            case "3":
                jTextAuthor.setEnabled(true);
                jTextAuthor1.setEnabled(true);
                jTextAuthor2.setEnabled(true);
                break;
        }
    }//GEN-LAST:event_jComboBoxAuthorInsertItemStateChanged

    private void jComboBoxAuthorEditItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxAuthorEditItemStateChanged
        // TODO add your handling code here:
        switch(jComboBoxAuthorEdit.getSelectedItem().toString()){
            case "1":
                jTextAuthorEdit.setEnabled(true);
                jTextAuthor1Edit.setEnabled(false);
                jTextAuthor2Edit.setEnabled(false);
                break;
            case "2":
                jTextAuthorEdit.setEnabled(true);
                jTextAuthor1Edit.setEnabled(true);
                jTextAuthor2Edit.setEnabled(false);
                break;
            case "3":
                jTextAuthorEdit.setEnabled(true);
                jTextAuthor1Edit.setEnabled(true);
                jTextAuthor2Edit.setEnabled(true);
                break;
            
        }
    }//GEN-LAST:event_jComboBoxAuthorEditItemStateChanged

    private void jButtonConsultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultActionPerformed
        // TODO add your handling code here:
        ShortCourseCrud.consult(jComboBoxConsult.getSelectedItem().toString(), jTextConsult.getText());
        ShortCourseCrud.list(jListNamesShortCourses);
    }//GEN-LAST:event_jButtonConsultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelShortCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelShortCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelShortCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelShortCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelShortCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackInsertInit;
    private javax.swing.JButton jButtonBackList;
    private javax.swing.JButton jButtonBackListInit;
    private javax.swing.JButton jButtonConsult;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonMoreDetails;
    private javax.swing.JButton jButtonSaveEdit;
    private javax.swing.JButton jButtonSaveInsert;
    private javax.swing.JComboBox<String> jComboBoxAuthorEdit;
    private javax.swing.JComboBox<String> jComboBoxAuthorInsert;
    private javax.swing.JComboBox<String> jComboBoxConsult;
    private javax.swing.JComboBox<String> jComboBoxSituation;
    private javax.swing.JComboBox<String> jComboBoxSituationEdit;
    private javax.swing.JFormattedTextField jFormattedDuration;
    private javax.swing.JFormattedTextField jFormattedDurationEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAbstractText;
    private javax.swing.JLabel jLabelAbstractTextEdit;
    private javax.swing.JLabel jLabelAuthor;
    private javax.swing.JLabel jLabelAuthorEdit;
    private javax.swing.JLabel jLabelConsult;
    private javax.swing.JLabel jLabelDuration;
    private javax.swing.JLabel jLabelDurationEdit;
    private javax.swing.JLabel jLabelMethodologyEdit;
    private javax.swing.JLabel jLabelResources;
    private javax.swing.JLabel jLabelResourcesEdit;
    private javax.swing.JLabel jLabelResumoText;
    private javax.swing.JLabel jLabelResumoTextEdit;
    private javax.swing.JLabel jLabelSituation;
    private javax.swing.JLabel jLabelSituationEdit;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTitleEdit;
    private javax.swing.JList<String> jListNamesShortCourses;
    private javax.swing.JPanel jPanelEdit;
    private javax.swing.JPanel jPanelInsert;
    private javax.swing.JPanel jPanelList;
    private javax.swing.JScrollPane jScrollPaneAbstractText;
    private javax.swing.JScrollPane jScrollPaneAbstractTextEdit;
    private javax.swing.JScrollPane jScrollPaneMethodology;
    private javax.swing.JScrollPane jScrollPaneMethodologyEdit;
    private javax.swing.JScrollPane jScrollPaneNamesShortCourses;
    private javax.swing.JScrollPane jScrollPaneResumoText;
    private javax.swing.JScrollPane jScrollPaneResumoTextEdit;
    private javax.swing.JTabbedPane jTabShortCourse;
    private javax.swing.JTextField jTextAuthor;
    private javax.swing.JTextField jTextAuthor1;
    private javax.swing.JTextField jTextAuthor1Edit;
    private javax.swing.JTextField jTextAuthor2;
    private javax.swing.JTextField jTextAuthor2Edit;
    private javax.swing.JTextField jTextAuthorEdit;
    private javax.swing.JTextField jTextConsult;
    private javax.swing.JTextPane jTextPaneAbstractText;
    private javax.swing.JTextPane jTextPaneAbstractTextEdit;
    private javax.swing.JTextPane jTextPaneMethodology;
    private javax.swing.JTextPane jTextPaneMethodologyEdit;
    private javax.swing.JTextPane jTextPaneResumoText;
    private javax.swing.JTextPane jTextPaneResumoTextEdit;
    private javax.swing.JTextField jTextResources;
    private javax.swing.JTextField jTextResourcesEdit;
    private javax.swing.JTextField jTextTitle;
    private javax.swing.JTextField jTextTitleEdit;
    // End of variables declaration//GEN-END:variables
}
