/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import categorias.Artigo;
import categorias.Minicurso;
import categorias.Monografia;
import categorias.Palestra;
import categorias.Resumo;
import categorias.Situacao;
import categorias.Submissao;
import categorias.SubmissaoApresentacao;
import categorias.SubmissaoCientifica;
import categorias.SubmissaoTipo;
import categorias.Tipo;
import cruds.SubmissaoCrud;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class SubmissoesFrame extends javax.swing.JFrame {

    private boolean isEdit;
    private SubmissaoCrud listaSubmissao;
    private Submissao submissaoSelecionada;
    private String tituloAnterior;
    private int contAutores = 0;
    private int contInstituicoes = 0;

    /**
     * Construtor para o caso de adição de nova submissao
     *
     * @param listaSubmissao
     */
    public SubmissoesFrame(SubmissaoCrud listaSubmissao, boolean isEdit, Submissao submissaoSelecionada) {

        initComponents();
        this.setLocationRelativeTo(null);
        this.submissaoSelecionada = submissaoSelecionada;
        this.isEdit = isEdit;
        this.listaSubmissao = listaSubmissao;

        if (isEdit) {
            tituloAnterior = submissaoSelecionada.getTituloSubmissao();
        }

        for (Situacao e : Situacao.values()) {
            jComboBoxSituacao.addItem(e.getSituacao());
        }

        switch (listaSubmissao.getTipoSubmissao()) {
            case Monografia:
                layoutMonografia();
                break;
            case Resumo:
                layoutResumo();
                break;
            case Palestra:
                layoutPalestra();
                break;
            case Minicurso:
                layoutMinicurso();
                break;
            case Artigo:
                layoutArtigo();
                break;
        }

    }

    /**
     * construtor para edição de uma submissao selecionada
     *
     * @param listaSubmissao
     * @param submissaoSelecionada
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldAutor1 = new javax.swing.JTextField();
        jTextFieldAutor2 = new javax.swing.JTextField();
        jTextFieldAutor3 = new javax.swing.JTextField();
        jTextFieldAutor4 = new javax.swing.JTextField();
        jTextFieldAutor5 = new javax.swing.JTextField();
        jTextFieldAutor6 = new javax.swing.JTextField();
        jTextFieldAutor7 = new javax.swing.JTextField();
        jTextFieldInstituicao1 = new javax.swing.JTextField();
        jTextFieldInstituicao2 = new javax.swing.JTextField();
        jTextFieldInstituicao3 = new javax.swing.JTextField();
        jTextFieldInstituicao4 = new javax.swing.JTextField();
        jTextFieldInstituicao5 = new javax.swing.JTextField();
        jTextFieldInstituicao6 = new javax.swing.JTextField();
        jTextFieldInstituicao7 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelLayoutGeral = new javax.swing.JPanel();
        jPanelSumissaoCientifica = new javax.swing.JPanel();
        jPanelInstituicoes = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldInstituicao0 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPalavra0 = new javax.swing.JTextField();
        jTextFieldPalavra1 = new javax.swing.JTextField();
        jTextFieldPalavra2 = new javax.swing.JTextField();
        jTextFieldPalavra3 = new javax.swing.JTextField();
        jPanelSubmissao = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jPanelAutores = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldAutor0 = new javax.swing.JTextField();
        jComboBoxSituacao = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabelTituloObrigatorio = new javax.swing.JLabel();
        jPanelSubmissaoApresentacao = new javax.swing.JPanel();
        jFormattedTextFieldDuracao = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanelResumoAbstract = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaAbstract = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaResumo = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanelBotoesAutores = new javax.swing.JPanel();
        jButtonAdicionarAutor = new javax.swing.JButton();
        jPanelBotoesInstituicoes = new javax.swing.JPanel();
        jButtonAdicionarInstituicao = new javax.swing.JButton();
        jPanelMonografia = new javax.swing.JPanel();
        jTextFieldCurso = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldOrientador = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldAno = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldNPaginas = new javax.swing.JTextField();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jPanelPalestra = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaCurriculo = new javax.swing.JTextArea();
        jPanelMinicurso = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaRecursos = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextAreaMetodologia = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jPanelBotoesControle = new javax.swing.JPanel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanelInstituicoes.setLayout(new java.awt.GridLayout(2, 0));

        jLabel2.setText("Instituição");
        jPanelInstituicoes.add(jLabel2);
        jPanelInstituicoes.add(jTextFieldInstituicao0);

        jLabel4.setText("Palavras Chave");

        javax.swing.GroupLayout jPanelSumissaoCientificaLayout = new javax.swing.GroupLayout(jPanelSumissaoCientifica);
        jPanelSumissaoCientifica.setLayout(jPanelSumissaoCientificaLayout);
        jPanelSumissaoCientificaLayout.setHorizontalGroup(
            jPanelSumissaoCientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSumissaoCientificaLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanelSumissaoCientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelSumissaoCientificaLayout.createSequentialGroup()
                        .addComponent(jTextFieldPalavra0, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldPalavra1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jTextFieldPalavra2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jTextFieldPalavra3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSumissaoCientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelInstituicoes, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(0, 0, 0))
        );
        jPanelSumissaoCientificaLayout.setVerticalGroup(
            jPanelSumissaoCientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSumissaoCientificaLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanelInstituicoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanelSumissaoCientificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPalavra0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPalavra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPalavra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPalavra3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabelTitulo.setText("Título");

        jTextFieldTitulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTituloFocusLost(evt);
            }
        });

        jPanelAutores.setLayout(new java.awt.GridLayout(2, 0, 1, 1));

        jLabel1.setText("Autor");
        jPanelAutores.add(jLabel1);
        jPanelAutores.add(jTextFieldAutor0);

        jLabel3.setText("Situação");

        javax.swing.GroupLayout jPanelSubmissaoLayout = new javax.swing.GroupLayout(jPanelSubmissao);
        jPanelSubmissao.setLayout(jPanelSubmissaoLayout);
        jPanelSubmissaoLayout.setHorizontalGroup(
            jPanelSubmissaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAutores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelSubmissaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelSubmissaoLayout.createSequentialGroup()
                .addGroup(jPanelSubmissaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelSubmissaoLayout.createSequentialGroup()
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190)
                        .addComponent(jLabelTituloObrigatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 317, Short.MAX_VALUE))
        );
        jPanelSubmissaoLayout.setVerticalGroup(
            jPanelSubmissaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSubmissaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSubmissaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTituloObrigatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        try {
            jFormattedTextFieldDuracao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDuracao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel6.setText("Duração");

        javax.swing.GroupLayout jPanelSubmissaoApresentacaoLayout = new javax.swing.GroupLayout(jPanelSubmissaoApresentacao);
        jPanelSubmissaoApresentacao.setLayout(jPanelSubmissaoApresentacaoLayout);
        jPanelSubmissaoApresentacaoLayout.setHorizontalGroup(
            jPanelSubmissaoApresentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSubmissaoApresentacaoLayout.createSequentialGroup()
                .addGroup(jPanelSubmissaoApresentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jFormattedTextFieldDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 617, Short.MAX_VALUE))
        );
        jPanelSubmissaoApresentacaoLayout.setVerticalGroup(
            jPanelSubmissaoApresentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSubmissaoApresentacaoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFormattedTextFieldDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaAbstract.setColumns(20);
        jTextAreaAbstract.setRows(5);
        jScrollPane2.setViewportView(jTextAreaAbstract);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaResumo.setColumns(20);
        jTextAreaResumo.setRows(5);
        jScrollPane3.setViewportView(jTextAreaResumo);

        jLabel7.setText("Resumo");

        jLabel8.setText("Abstract");

        javax.swing.GroupLayout jPanelResumoAbstractLayout = new javax.swing.GroupLayout(jPanelResumoAbstract);
        jPanelResumoAbstract.setLayout(jPanelResumoAbstractLayout);
        jPanelResumoAbstractLayout.setHorizontalGroup(
            jPanelResumoAbstractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResumoAbstractLayout.createSequentialGroup()
                .addGroup(jPanelResumoAbstractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(jPanelResumoAbstractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanelResumoAbstractLayout.setVerticalGroup(
            jPanelResumoAbstractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResumoAbstractLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanelResumoAbstractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(5, 5, 5)
                .addGroup(jPanelResumoAbstractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanelBotoesAutores.setLayout(new java.awt.GridLayout(1, 0));

        jButtonAdicionarAutor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAdicionarAutor.setText("+");
        jButtonAdicionarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarAutorActionPerformed(evt);
            }
        });
        jPanelBotoesAutores.add(jButtonAdicionarAutor);

        jPanelBotoesInstituicoes.setLayout(new java.awt.GridLayout(1, 0));

        jButtonAdicionarInstituicao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAdicionarInstituicao.setText("+");
        jButtonAdicionarInstituicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarInstituicaoActionPerformed(evt);
            }
        });
        jPanelBotoesInstituicoes.add(jButtonAdicionarInstituicao);

        jLabel5.setText("Curso");

        jLabel9.setText("Orientador");

        jLabel10.setText("Ano");

        jTextFieldAno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAnoKeyTyped(evt);
            }
        });

        jLabel11.setText("Numero de Paginas");

        jTextFieldNPaginas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNPaginasKeyTyped(evt);
            }
        });

        jLabel12.setText("Tipo");

        javax.swing.GroupLayout jPanelMonografiaLayout = new javax.swing.GroupLayout(jPanelMonografia);
        jPanelMonografia.setLayout(jPanelMonografiaLayout);
        jPanelMonografiaLayout.setHorizontalGroup(
            jPanelMonografiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldCurso)
            .addComponent(jTextFieldOrientador, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelMonografiaLayout.createSequentialGroup()
                .addGroup(jPanelMonografiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addGroup(jPanelMonografiaLayout.createSequentialGroup()
                        .addGroup(jPanelMonografiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanelMonografiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldNPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(43, 43, 43)
                        .addGroup(jPanelMonografiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelMonografiaLayout.setVerticalGroup(
            jPanelMonografiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMonografiaLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(7, 7, 7)
                .addComponent(jTextFieldCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldOrientador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMonografiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(5, 5, 5)
                .addGroup(jPanelMonografiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel13.setText("Curriculo");

        jTextAreaCurriculo.setColumns(20);
        jTextAreaCurriculo.setRows(5);
        jScrollPane4.setViewportView(jTextAreaCurriculo);

        javax.swing.GroupLayout jPanelPalestraLayout = new javax.swing.GroupLayout(jPanelPalestra);
        jPanelPalestra.setLayout(jPanelPalestraLayout);
        jPanelPalestraLayout.setHorizontalGroup(
            jPanelPalestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPalestraLayout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane4)
        );
        jPanelPalestraLayout.setVerticalGroup(
            jPanelPalestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPalestraLayout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel14.setText("Recursos");

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaRecursos.setColumns(20);
        jTextAreaRecursos.setRows(5);
        jScrollPane5.setViewportView(jTextAreaRecursos);

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaMetodologia.setColumns(20);
        jTextAreaMetodologia.setRows(5);
        jScrollPane6.setViewportView(jTextAreaMetodologia);

        jLabel15.setText("Metodologia");

        javax.swing.GroupLayout jPanelMinicursoLayout = new javax.swing.GroupLayout(jPanelMinicurso);
        jPanelMinicurso.setLayout(jPanelMinicursoLayout);
        jPanelMinicursoLayout.setHorizontalGroup(
            jPanelMinicursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMinicursoLayout.createSequentialGroup()
                .addGroup(jPanelMinicursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMinicursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanelMinicursoLayout.setVerticalGroup(
            jPanelMinicursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMinicursoLayout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelMinicursoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanelLayoutGeralLayout = new javax.swing.GroupLayout(jPanelLayoutGeral);
        jPanelLayoutGeral.setLayout(jPanelLayoutGeralLayout);
        jPanelLayoutGeralLayout.setHorizontalGroup(
            jPanelLayoutGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayoutGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayoutGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayoutGeralLayout.createSequentialGroup()
                        .addGroup(jPanelLayoutGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelSubmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelSumissaoCientifica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayoutGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelBotoesInstituicoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelBotoesAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelLayoutGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanelMinicurso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelPalestra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelMonografia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelResumoAbstract, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanelSubmissaoApresentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelLayoutGeralLayout.setVerticalGroup(
            jPanelLayoutGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayoutGeralLayout.createSequentialGroup()
                .addGroup(jPanelLayoutGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayoutGeralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelSubmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayoutGeralLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jPanelBotoesAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayoutGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSumissaoCientifica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelLayoutGeralLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanelBotoesInstituicoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addComponent(jPanelSubmissaoApresentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMonografia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelResumoAbstract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelPalestra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelMinicurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanelLayoutGeral);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotoesControleLayout = new javax.swing.GroupLayout(jPanelBotoesControle);
        jPanelBotoesControle.setLayout(jPanelBotoesControleLayout);
        jPanelBotoesControleLayout.setHorizontalGroup(
            jPanelBotoesControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesControleLayout.createSequentialGroup()
                .addComponent(jButtonCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalvar))
        );
        jPanelBotoesControleLayout.setVerticalGroup(
            jPanelBotoesControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotoesControleLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanelBotoesControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonSalvar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanelBotoesControle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelBotoesControle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
        new ListarFrame(this.listaSubmissao).setVisible(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAdicionarInstituicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarInstituicaoActionPerformed

        switch (++contInstituicoes) {
            case 1:
                jPanelInstituicoes.add(jTextFieldInstituicao1);
                break;
            case 2:
                jPanelInstituicoes.add(jTextFieldInstituicao2);
                break;
            case 3:
                jPanelInstituicoes.add(jTextFieldInstituicao3);
                break;
            case 4:
                jPanelInstituicoes.add(jTextFieldInstituicao4);
                break;
            case 5:
                jPanelInstituicoes.add(jTextFieldInstituicao5);
                break;
            case 6:
                jPanelInstituicoes.add(jTextFieldInstituicao6);
                break;
            case 7:
                jPanelInstituicoes.add(jTextFieldInstituicao7);
                break;
        }
        jPanelInstituicoes.setLayout(new GridLayout(0, 1, 2, 2));

        this.revalidate();
        this.repaint();

    }//GEN-LAST:event_jButtonAdicionarInstituicaoActionPerformed

    private void jButtonAdicionarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarAutorActionPerformed

        switch (++contAutores) {
            case 1:
                jPanelAutores.add(jTextFieldAutor1);
                break;
            case 2:
                jPanelAutores.add(jTextFieldAutor2);
                break;
            case 3:
                jPanelAutores.add(jTextFieldAutor3);
                break;
            case 4:
                jPanelAutores.add(jTextFieldAutor4);
                break;
            case 5:
                jPanelAutores.add(jTextFieldAutor5);
                break;
            case 6:
                jPanelAutores.add(jTextFieldAutor6);
                break;
            case 7:
                jPanelAutores.add(jTextFieldAutor7);
                break;
        }
        jPanelAutores.setLayout(new GridLayout(0, 1, 2, 2));

        if (contAutores == 2 && listaSubmissao.getTipoSubmissao().toString().equals(SubmissaoTipo.Minicurso.toString())) {
            jButtonAdicionarAutor.setEnabled(false);
        }

        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_jButtonAdicionarAutorActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        switch (listaSubmissao.getTipoSubmissao()) {
            case Monografia:
                submissaoSelecionada = new Monografia();
                salvarMonografia();
                break;
            case Resumo:
                submissaoSelecionada = new Resumo();
                salvarResumo();
                break;
            case Palestra:
                submissaoSelecionada = new Palestra();
                salvarPalestra();
                break;
            case Minicurso:
                submissaoSelecionada = new Minicurso();
                salvarMinicurso();
                break;
            case Artigo:
                submissaoSelecionada = new Artigo();
                salvarArtigo();
                break;
        }

        if (isEdit) {
            listaSubmissao.editar(tituloAnterior, submissaoSelecionada);
        } else {
            listaSubmissao.incluir(submissaoSelecionada);
        }

        this.dispose();
        new ListarFrame(listaSubmissao).setVisible(true);

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jTextFieldAnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAnoKeyTyped
        soNumeros(evt);
    }//GEN-LAST:event_jTextFieldAnoKeyTyped

    private void jTextFieldNPaginasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNPaginasKeyTyped
        soNumeros(evt);
    }//GEN-LAST:event_jTextFieldNPaginasKeyTyped

    private void jTextFieldTituloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTituloFocusLost
        if (jTextFieldTitulo.getText().trim().isEmpty()) {
            jButtonSalvar.setEnabled(false);
            jLabelTituloObrigatorio.setText("Campo Obrigatório");
        } else {
            jButtonSalvar.setEnabled(true);
            jLabelTituloObrigatorio.setText("");
        }
    }//GEN-LAST:event_jTextFieldTituloFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubmissoesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubmissoesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubmissoesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubmissoesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubmissoesFrame(null, false, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarAutor;
    private javax.swing.JButton jButtonAdicionarInstituicao;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxSituacao;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JFormattedTextField jFormattedTextFieldDuracao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTituloObrigatorio;
    private javax.swing.JPanel jPanelAutores;
    private javax.swing.JPanel jPanelBotoesAutores;
    private javax.swing.JPanel jPanelBotoesControle;
    private javax.swing.JPanel jPanelBotoesInstituicoes;
    private javax.swing.JPanel jPanelInstituicoes;
    private javax.swing.JPanel jPanelLayoutGeral;
    private javax.swing.JPanel jPanelMinicurso;
    private javax.swing.JPanel jPanelMonografia;
    private javax.swing.JPanel jPanelPalestra;
    private javax.swing.JPanel jPanelResumoAbstract;
    private javax.swing.JPanel jPanelSubmissao;
    private javax.swing.JPanel jPanelSubmissaoApresentacao;
    private javax.swing.JPanel jPanelSumissaoCientifica;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextAreaAbstract;
    private javax.swing.JTextArea jTextAreaCurriculo;
    private javax.swing.JTextArea jTextAreaMetodologia;
    private javax.swing.JTextArea jTextAreaRecursos;
    private javax.swing.JTextArea jTextAreaResumo;
    private javax.swing.JTextField jTextFieldAno;
    private javax.swing.JTextField jTextFieldAutor0;
    private javax.swing.JTextField jTextFieldAutor1;
    private javax.swing.JTextField jTextFieldAutor2;
    private javax.swing.JTextField jTextFieldAutor3;
    private javax.swing.JTextField jTextFieldAutor4;
    private javax.swing.JTextField jTextFieldAutor5;
    private javax.swing.JTextField jTextFieldAutor6;
    private javax.swing.JTextField jTextFieldAutor7;
    private javax.swing.JTextField jTextFieldCurso;
    private javax.swing.JTextField jTextFieldInstituicao0;
    private javax.swing.JTextField jTextFieldInstituicao1;
    private javax.swing.JTextField jTextFieldInstituicao2;
    private javax.swing.JTextField jTextFieldInstituicao3;
    private javax.swing.JTextField jTextFieldInstituicao4;
    private javax.swing.JTextField jTextFieldInstituicao5;
    private javax.swing.JTextField jTextFieldInstituicao6;
    private javax.swing.JTextField jTextFieldInstituicao7;
    private javax.swing.JTextField jTextFieldNPaginas;
    private javax.swing.JTextField jTextFieldOrientador;
    private javax.swing.JTextField jTextFieldPalavra0;
    private javax.swing.JTextField jTextFieldPalavra1;
    private javax.swing.JTextField jTextFieldPalavra2;
    private javax.swing.JTextField jTextFieldPalavra3;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables

    private void layoutMonografia() {
        jPanelSubmissaoApresentacao.removeAll();
        jPanelBotoesAutores.removeAll();
        jPanelBotoesInstituicoes.removeAll();
        jPanelMinicurso.removeAll();
        jPanelPalestra.removeAll();

        for (Tipo e : Tipo.values()) {
            jComboBoxTipo.addItem(e.getTipo());
        }

        if (isEdit) {
            setEditarSubmissaoCientifica();

            Monografia submissao = (Monografia) submissaoSelecionada;
            jTextFieldAno.setText(String.valueOf(submissao.getAno()));
            jTextFieldCurso.setText(submissao.getCurso());
            jTextFieldOrientador.setText(submissao.getOrientador());
            jTextFieldNPaginas.setText(String.valueOf(submissao.getnPaginas()));

            for (int i = 0; i < 4; i++) {
                if (jComboBoxTipo.getItemAt(i).equalsIgnoreCase(submissao.getTipo().toString())) {
                    jComboBoxTipo.setSelectedIndex(i);
                }
            }

            jTextAreaAbstract.setText(submissao.getAbstractText());
            jTextAreaResumo.setText(submissao.getResumo());
        }

    }

    private void layoutResumo() {
        jPanelMinicurso.removeAll();
        jPanelPalestra.removeAll();
        jPanelMonografia.removeAll();
        jPanelSubmissaoApresentacao.removeAll();
        jPanelResumoAbstract.removeAll();

        if (isEdit) {
            setEditarSubmissaoCientifica();
        }
    }

    private void layoutPalestra() {
        jPanelMinicurso.removeAll();
        jPanelMonografia.removeAll();
        jPanelSumissaoCientifica.removeAll();
        jPanelBotoesInstituicoes.removeAll();
        jPanelBotoesAutores.removeAll();

        if (isEdit) {
            setEditarSubmissaoApresetacao();
            Palestra submissao = (Palestra) submissaoSelecionada;
            jTextAreaCurriculo.setText(submissao.getCurriculo());
        }

    }

    private void layoutMinicurso() {
        jPanelPalestra.removeAll();
        jPanelMonografia.removeAll();
        jPanelSumissaoCientifica.removeAll();
        jPanelBotoesInstituicoes.removeAll();

        if (isEdit) {
            setEditarSubmissaoApresetacao();
            Minicurso submissao = (Minicurso) submissaoSelecionada;
            jTextAreaRecursos.setText(submissao.getRecursos());
            jTextAreaMetodologia.setText(submissao.getMetodologia());
        }

    }

    private void layoutArtigo() {
        jPanelPalestra.removeAll();
        jPanelMonografia.removeAll();
        jPanelMinicurso.removeAll();
        jPanelSubmissaoApresentacao.removeAll();
        if (isEdit) {
            setEditarSubmissaoCientifica();
            Artigo submissao = (Artigo) submissaoSelecionada;

            jTextAreaAbstract.setText(submissao.getAbstractText());
            jTextAreaResumo.setText(submissao.getResumo());

        }

    }

    private void setEditarSubmissao() {
        jTextFieldTitulo.setText(submissaoSelecionada.getTituloSubmissao());

        submissaoSelecionada.getAutores().size();

        for (int i = 0; i < submissaoSelecionada.getAutores().size(); i++) {
            switch (i) {
                case 0:
                    jTextFieldAutor0.setText(submissaoSelecionada.getAutores().get(0));
                    break;
                case 1:
                    jTextFieldAutor1.setText(submissaoSelecionada.getAutores().get(1));
                    break;
                case 2:
                    jTextFieldAutor2.setText(submissaoSelecionada.getAutores().get(2));
                    break;
                case 3:
                    jTextFieldAutor3.setText(submissaoSelecionada.getAutores().get(3));
                    break;
                case 4:
                    jTextFieldAutor4.setText(submissaoSelecionada.getAutores().get(4));
                    break;
                case 5:
                    jTextFieldAutor5.setText(submissaoSelecionada.getAutores().get(5));
                    break;
                case 6:
                    jTextFieldAutor6.setText(submissaoSelecionada.getAutores().get(6));
                    break;
                case 7:
                    jTextFieldAutor7.setText(submissaoSelecionada.getAutores().get(7));
                    break;
            }
            if (i > 0) {
                jButtonAdicionarAutor.doClick();
            }
        }

        for (int i = 0; i < 3; i++) {
            if (jComboBoxSituacao.getItemAt(i).equalsIgnoreCase(submissaoSelecionada.getSituacaoSubmissao().toString())) {
                jComboBoxSituacao.setSelectedIndex(i);
            }
        }

    }

    private void setEditarSubmissaoCientifica() {

        setEditarSubmissao();
        SubmissaoCientifica submissao = (SubmissaoCientifica) submissaoSelecionada;

        for (int i = 0; i < submissao.getInstituicao().size(); i++) {
            switch (i) {
                case 0:
                    jTextFieldInstituicao0.setText(submissao.getInstituicao().get(0));
                    break;
                case 1:
                    jTextFieldInstituicao1.setText(submissao.getInstituicao().get(1));
                    break;
                case 2:
                    jTextFieldInstituicao2.setText(submissao.getInstituicao().get(2));
                    break;
                case 3:
                    jTextFieldInstituicao3.setText(submissao.getInstituicao().get(3));
                    break;
                case 4:
                    jTextFieldInstituicao4.setText(submissao.getInstituicao().get(4));
                    break;
                case 5:
                    jTextFieldInstituicao5.setText(submissao.getInstituicao().get(5));
                    break;
                case 6:
                    jTextFieldInstituicao6.setText(submissao.getInstituicao().get(6));
                    break;
                case 7:
                    jTextFieldInstituicao7.setText(submissao.getInstituicao().get(7));
                    break;
            }
            if (i > 0) {
                jButtonAdicionarInstituicao.doClick();
            }
        }

        jTextFieldPalavra0.setText(submissao.getPalavraChave().get(0));
        jTextFieldPalavra1.setText(submissao.getPalavraChave().get(1));
        jTextFieldPalavra2.setText(submissao.getPalavraChave().get(2));
        jTextFieldPalavra3.setText(submissao.getPalavraChave().get(3));

    }

    private void setEditarSubmissaoApresetacao() {
        String duracaoEditar;
        int hora, minutos, segundos;

        setEditarSubmissao();
        SubmissaoApresentacao submissao = (SubmissaoApresentacao) submissaoSelecionada;

        hora = submissao.getDuracao() / 3600;
        minutos = (submissao.getDuracao() % 3600) / 60;
        segundos = (submissao.getDuracao() % 3600) % 60;

        if (segundos < 10 && hora < 10 && minutos < 10) {
            duracaoEditar = "0" + String.valueOf(hora) + "0" + String.valueOf(minutos)
                    + "0" + String.valueOf(segundos);
        } else if (segundos < 10 && hora < 10) {
            duracaoEditar = "0" + String.valueOf(hora) + String.valueOf(minutos)
                    + "0" + String.valueOf(segundos);
        } else if (segundos < 10 && minutos < 10) {
            duracaoEditar = String.valueOf(hora) + "0" + String.valueOf(minutos)
                    + "0" + String.valueOf(segundos);
        } else if (hora < 10 && minutos < 10) {
            duracaoEditar = "0" + String.valueOf(hora) + "0" + String.valueOf(minutos)
                    + String.valueOf(segundos);
        } else if (hora < 10) {
            duracaoEditar = "0" + String.valueOf(hora) + String.valueOf(minutos)
                    + String.valueOf(segundos);
        } else if (minutos < 10) {
            duracaoEditar = String.valueOf(hora) + "0" + String.valueOf(minutos)
                    + String.valueOf(segundos);
        } else if (segundos < 10) {
            duracaoEditar = String.valueOf(hora) + String.valueOf(minutos)
                    + "0" + String.valueOf(segundos);
        } else {
            duracaoEditar = String.valueOf(hora) + String.valueOf(minutos)
                    + String.valueOf(segundos);
        }

        jFormattedTextFieldDuracao.setText(duracaoEditar);
        jTextAreaAbstract.setText(submissao.getAbstractText());
        jTextAreaResumo.setText(submissao.getResumo());

    }

    private void salvarSubmissao() {

        submissaoSelecionada.setTituloSubmissao(jTextFieldTitulo.getText());
        submissaoSelecionada.setSituacaoSubmissao(Situacao.verificarSituacao(jComboBoxSituacao.getSelectedItem().toString()));

        List<String> autores = new ArrayList();

        for (int i = 0; i < contAutores + 1; i++) {
            switch (i) {
                case 0:
                    autores.add(jTextFieldAutor0.getText());
                    break;
                case 1:
                    autores.add(jTextFieldAutor1.getText());
                    break;
                case 2:
                    autores.add(jTextFieldAutor2.getText());
                    break;
                case 3:
                    autores.add(jTextFieldAutor3.getText());
                    break;
                case 4:
                    autores.add(jTextFieldAutor4.getText());
                    break;
                case 5:
                    autores.add(jTextFieldAutor5.getText());
                    break;
                case 6:
                    autores.add(jTextFieldAutor6.getText());
                    break;
                case 7:
                    autores.add(jTextFieldAutor7.getText());
                    break;
            }
        }

        submissaoSelecionada.setAutores(autores);

    }

    private void salvarSubmissaoCientifica() {

        salvarSubmissao();

        SubmissaoCientifica submissao = (SubmissaoCientifica) submissaoSelecionada;
        List<String> instituicoes = new ArrayList();
        List<String> palavras = new ArrayList();

        for (int i = 0; i < contAutores + 1; i++) {
            switch (i) {
                case 0:
                    instituicoes.add(jTextFieldInstituicao0.getText());
                    break;
                case 1:
                    instituicoes.add(jTextFieldInstituicao1.getText());
                    break;
                case 2:
                    instituicoes.add(jTextFieldInstituicao2.getText());
                    break;
                case 3:
                    instituicoes.add(jTextFieldInstituicao3.getText());
                    break;
                case 4:
                    instituicoes.add(jTextFieldInstituicao4.getText());
                    break;
                case 5:
                    instituicoes.add(jTextFieldInstituicao5.getText());
                    break;
                case 6:
                    instituicoes.add(jTextFieldInstituicao6.getText());
                    break;
                case 7:
                    instituicoes.add(jTextFieldInstituicao7.getText());
                    break;
            }
        }

        palavras.add(jTextFieldPalavra0.getText());
        palavras.add(jTextFieldPalavra1.getText());
        palavras.add(jTextFieldPalavra2.getText());
        palavras.add(jTextFieldPalavra3.getText());

        submissao.setInstituicao(instituicoes);
        submissao.setPalavraChave(palavras);

        submissaoSelecionada = submissao;

    }

    private void salvarSubmissaoApresentacao() {
        int duracao;

        salvarSubmissao();
        SubmissaoApresentacao submissao = (SubmissaoApresentacao) submissaoSelecionada;

        submissao.setAbstractText(jTextAreaAbstract.getText());
        submissao.setResumo(jTextAreaResumo.getText());

        if (verificarDuracao(jFormattedTextFieldDuracao.getText())) {
            JOptionPane.showMessageDialog(null, "Duração inválida");
        }

        duracao = converterStringEmNumero(jFormattedTextFieldDuracao.getText());
        submissao.setDuracao(duracao);
        submissaoSelecionada = submissao;

    }

    private void salvarMonografia() {

        salvarSubmissaoCientifica();

        Monografia submissao = (Monografia) submissaoSelecionada;

        submissao.setAbstractText(jTextAreaAbstract.getText());

        submissao.setResumo(jTextAreaResumo.getText());
        if (jTextFieldAno.getText().isEmpty() == false) {
            submissao.setAno(Integer.parseInt(jTextFieldAno.getText()));
        }
        submissao.setCurso(jTextFieldCurso.getText());
        submissao.setOrientador(jTextFieldOrientador.getText());
        if (jTextFieldNPaginas.getText().isEmpty() == false) {
            submissao.setnPaginas(Integer.parseInt(jTextFieldNPaginas.getText()));
        }
        submissao.setTipo(Tipo.verificarTipo(jComboBoxTipo.getSelectedItem().toString()));

        submissaoSelecionada = submissao;

    }

    private void salvarPalestra() {

        salvarSubmissaoApresentacao();
        Palestra submissao = (Palestra) submissaoSelecionada;
        submissao.setCurriculo(jTextAreaCurriculo.getText());
        submissaoSelecionada = submissao;

    }

    private void salvarMinicurso() {

        salvarSubmissaoApresentacao();
        Minicurso submissao = (Minicurso) submissaoSelecionada;

        submissao.setMetodologia(jTextAreaMetodologia.getText());
        submissao.setRecursos(jTextAreaRecursos.getText());

        submissaoSelecionada = submissao;

    }

    private void salvarResumo() {
        salvarSubmissaoCientifica();
    }

    private void salvarArtigo() {

        salvarSubmissaoCientifica();
        Artigo submissao = (Artigo) submissaoSelecionada;
        submissao.setAbstrat(jTextAreaAbstract.getText());
        submissao.setResumo(jTextAreaResumo.getText());
        submissaoSelecionada = submissao;

    }

    public boolean verificarDuracao(String duracaoString) {
        for (int i = 0; i < duracaoString.length(); i++) {
            if (Integer.parseInt(duracaoString.substring(3, 5)) >= 60) {
                return true;
            } else if (Integer.parseInt(duracaoString.substring(6)) >= 60) {
                return true;
            } else if (Integer.parseInt(duracaoString.substring(3, 5)) <= 19
                    && Integer.parseInt(duracaoString.substring(0, 2)) == 00) {
                return true;
            }
        }
        return false;
    }

    public int converterStringEmNumero(String duracaoString) {
        int duracao = 0;

        duracao += Integer.parseInt(duracaoString.substring(0, 2)) * 3600;
        duracao += Integer.parseInt(duracaoString.substring(3, 5)) * 60;
        duracao += Integer.parseInt(duracaoString.substring(6));

        return duracao;
    }

    private void soNumeros(java.awt.event.KeyEvent evt) {
        char ch = evt.getKeyChar();
        if (ch >= '0' && ch <= '9') {

        } else {
            evt.consume();
        }
    }

}
